### ISSUE TITLE
Seems like docs were not parsed

### ISSUE THREAD

**Issue by lexrus** [Alamofire/AlamofireImage#1]
I wanna read the doc but after clicking the link in the README:
http://cocoadocs.org/docsets/AlamofireImage/1.0.0-beta.1/

I found:
```
Error Parsing Pod
Could not find Objective-C Classes.
```

**Comment by cnoon** [comment]
It appears to be happening on Alamofire as well. My guess is that this is due to the fact that it is a pre-release or that the tag contains the word `beta`.

**Comment by cnoon** [comment]
I'm going to go ahead and close this issue out @lexrus. Thank you for reporting. I will re-open if this is not resolved with the 1.0.0 release.

**Comment by onevcat** [comment]
It seems the [jazzy](https://github.com/Realm/jazzy) only works for Swift 1.x style documentation. I think we could wait for the release of Swift 2 and see whether there's a change on it.

**Comment by cnoon** [comment]
Cool...thanks for the heads up @onevcat!

**Comment by orta** [comment]
Yeah, this is a Swift 2 issue :+1: - I've not updated CocoaDocs to Xc7 yet. Presuming we get some stability this week, I'll be migrating.

**Comment by cnoon** [comment]
Sounds good @orta. Thanks for the info.
