### ISSUE TITLE
Any way to preload images into the cache?

### ISSUE THREAD

**Issue by tfe** [Alamofire/AlamofireImage#104]
Let's say I have an array of image URLs that I know I'm going to need soon... is there any way to preload these into the cache so that they can start downloading immediately?

**Comment by dingua** [comment]
i am doing the same, for that i download the images and i add them to the cache `AutoPurgingImageCache` by the method `addImage` , next time when i need to access to the image i check if it is in the cache or not using the method `imageWithIdentifier` and i give as parameter the image's `identifier` that i used when adding it to the cache.

**Comment by kishorer747** [comment]
Yes, you can download all the images and add them to cache individually. But it would have been great if there was a method to directly download and cache a list of image URL's
And you don't need to check if the image is in cache or not before using it.
From the docs: [https://github.com/Alamofire/AlamofireImage#setting-image-with-url](https://github.com/Alamofire/AlamofireImage#setting-image-with-url)

`let imageView = UIImageView(frame: frame)
let URL = NSURL(string: "https://httpbin.org/image/png")!

imageView.af_setImageWithURL(URL)`

> If the image is cached locally, the image is set immediately.

**Comment by kcharwood** [comment]
Yes you can certainly do this.

On the [Image Downloader](https://github.com/Alamofire/AlamofireImage/blob/master/Source/ImageDownloader.swift#L431-L437), call `downloadImages`. You can fire and forget, and if they get back in time they will pull from cache.

**Comment by kean** [comment]
You may probably borrow some ideas from [Nuke](https://github.com/kean/Nuke). it has a special API for `precaching` images:

```swift
func startPreheatingImages(requests: [ImageRequest])
func stopPreheatingImages(requests: [ImageRequest])
func stopPreheatingImages()
```

It registers given requests for precaching. Actual networking/cache tasks are not executed until there are no outstanding regular (non-precaching) tasks.

I find this very useful. If you need more info you may also check out [this post](http://outscope.net/blog/image-preheating). 

I've also implemented a separate [Preheat](https://github.com/kean/Preheat) library that allows to automates precaching of content in `UITableView` and `UICollectionView`. It can be used with `Alamofire` as well as any other image loading library.

**Comment by kishorer747** [comment]
@kcharwood @kean 
If i use downloadImages by sending a list of URL's, on completion of download of all images, will these images be added to cache? And if so, the forRequest parameter we used to send for .downloadImage is not there in downloadImages method

Basically i am asking if i fire and forget, will these images be added to cache and next time the same url is accessed, the image is loaded from cache?

**Comment by bendecoste** [comment]
> Basically i am asking if i fire and forget, will these images be added to cache and next time the same url is accessed, the image is loaded from cache?

You can do this.  As long as the image downloader instance you are using is the same as the one you use to download the images later.  In my case an implementation looked like this

```swift
// precaching done here
UIImageView.af_sharedImageDownloader.downloadImages(URLRequests: requests)

// later, when setting content on some imageview
// as long as url was in the array of URLRequests above, the cached version will be used
imageView.af_setImageWithURL(url, placeholderImage: UIImage(named: "grey-image-placeholder"), filter: nil, imageTransition: .CrossDissolve(0.5))
```

**Comment by cnoon** [comment]
Thanks @kcharwood and @bendecoste! I'm going to close this issue out since I believe all the open questions have been addressed.

Cheers. 🍻
