### ISSUE TITLE
ImageCache.removeAllImagesForRequest() aka. glob/wildcard

### ISSUE THREAD

**Issue by neoneye** [Alamofire/AlamofireImage#105]
First of all AlamofireImage is awesome.

My code looks like this

```swift
let size = imageView.frame.size
imageView.af_setImageWithURL(
	url,
	placeholderImage: placeholderImage,
	filter: MyFilter(size: size),
	imageTransition: .CrossDissolve(0.2)
)
```

Often I would like to remove all images for a particular url, because the user have performed a destructive action, that may invalidate thumbnails.

Internally the identifier that it's being used is `http://example.com/thumbnail/42-MyFilter-size:(60x60)`

I would like to remove everything that starts with `http://example.com/thumbnail/42`

**Comment by cnoon** [comment]
Hi @neoneye, I'm going to close this issue out. Let's redirect all future comments to #106.
