### ISSUE TITLE
Certain images not loading with af_setImageWithURL

### ISSUE THREAD

**Issue by kevinmanncito** [Alamofire/AlamofireImage#108]
There seems to be certain images that never load with `af_setImageWithURL`.  Here is a snippet that can be run in an iOS playground and you will see the issue:

```
import UIKit
import XCPlayground
import AlamofireImage

let container = UIView(frame: CGRectMake(0, 0, 100, 200))

let goodImage = UIImageView(frame: CGRectMake(0, 0, 100, 100))
goodImage.af_setImageWithURL(NSURL(string: "https://slack-imgs.com/?url=http%3A%2F%2Fhelp.plot.ly%2Fimages%2Ftwitter-default.png")!)

let badImage = UIImageView(frame: CGRectMake(0, 100, 100, 100))
badImage.af_setImageWithURL(NSURL(string: "https://hammerprice-dev-staging.s3.amazonaws.com/image/by-md5/4/8/48290c3829540daee4e2bd45b1c38f68/Test3.jpg")!)

container.addSubview(goodImage)
container.addSubview(badImage)

XCPlaygroundPage.currentPage.liveView = container
```

Here is a screenshot of the playground output:

![screen shot 2016-05-11 at 5 15 48 pm](https://cloud.githubusercontent.com/assets/2521298/15199525/1b833496-179c-11e6-927e-9c5e366847bd.png)

There are no errors happening in the console, the image just never loads. The main difference I can see  between these two image urls is the slack image will open directly in a browser but the hammerprice url goes straight to a download page when opened in a browser. Not sure what that means. Any ideas? Thanks!

Using XCode 7.3 and iOS 9.x

**Comment by jshier** [comment]
Most likely this is due to the second server returning the `Content-Type: binary/octet-stream` header, which is not a valid image format. If you run `Request.acceptableImageTypes.insert("binary/octet-stream")` before issuing that request it should work. Really though, you want to fix the server to return proper image types.

**Comment by kevinmanncito** [comment]
Ahh... that makes sense. Should have checked the request headers.

**Comment by jshier** [comment]
Feel free to reopen if that doesn't fix it.

**Comment by kevinmanncito** [comment]
We are good, it fixed it. Thanks again.
