### ISSUE TITLE
Caching of images with pre-signed URL's

### ISSUE THREAD

**Issue by kaspermunck** [Alamofire/AlamofireImage#109]
We use AWS for storing images and other assets. All our resource URL's are always signed and they look something like this: 

```
https://our-aws-api.com/1e694fa00dac5bae71fe865f25117756a915118f.jpg?AWSAccessKeyId=MHSUQFKDUWROKGJSUI&Expires=1463062749&Signature=h2asdrt%2KDJSIAMtIasdzH6KgJDKSjw%3D
```

This does not work well with the caching mechanism of ImageDownloader, which identifies a resource by its absolute URL. See `ImageDownloader.swift`, line 527:

```
static func identifierForURLRequest(URLRequest: URLRequestConvertible) -> String {
        return URLRequest.URLRequest.URLString
    }
```

Where the implementation of `URLString` returns the value of the request URL's `absoluteString`.

Would it be an idea to provide a hook to provide a custom identifier for a given resource when scheduling the download? In our case, the image names (without signature parameters) would be sufficient, but I am not aware if this would work in all cases. Or is there already a mechanism in AlamofireImage that handles signed URL's that I am not aware of?

*Update*
After reading up on `NSURLCache`, which works out of the box/under the hood when using Foundation's URL*-classes, it's clear that the problem is not the in-memory Alamofire cache, but the `NSURLCache`. It cashes the `NSURLRequest`, probably using the absolute URL as well, and it looks like there's no way to change this.

**Comment by cnoon** [comment]
You nailed i @kaspermunck...I don't think there's really anything we can do for that type of URL in AFI. Everything stored on-disk is using the `NSURLCache` which is what you're getting bit by. 

If you really need more intelligent caching, you could build your own `ImageCache` that can persist images on-disk. However, I'd caution you to make sure this is absolutely necessary before doing so, b/c implementing an on-disk image cache is not trivial.

I'm going to go ahead and close this issue out @kaspermunck since I don't think there's an actionable item on our part. Please feel free to keep commenting on this ticket if you have additional questions or more info.

Cheers. 🍻

**Comment by kaspermunck** [comment]
That's what I thought. Spinning up our own on-disk cache is definitely not something we wanted. Instead, when requesting a private image resource from Amazon, we hit a static URL on our own server, which then forwards the request to Amazon's signed URL. It works very well for us, but comes with a few caveats: 

- We must hit our own server before forwarding, which obviously increases the traffic. However, since it's merely an HTTP forwarding, it hasn't revealed any performance issues yet.
- It does require a bit of client-side logic, where we have to hook into `NSURLSession`'s `dataTask:willCacheResponse...` and the `Manager`'s `taskWillPerformHTTPRedirection` methods and do a bit of work to remember the original (pre-forwarding) request, because the request will chance during the HTTP-forwarding.

Thanks for your time looking at the issue though.

**Comment by georgel** [comment]
Is there a way to implement cache key filter so we can use AlamofireImage directly with Amazon's signed URL?

SDWebImage had a similar issue that was resolved with something like 

```
func registerSDWebImage() {
		SDWebImageManager.sharedManager().cacheKeyFilter = { url in			
			let components = NSURLComponents()
			components.scheme = url.scheme
			components.host = url.host
			components.path = url.path!
			return components.URL!.absoluteString
		}
	}
```
