### ISSUE TITLE
ETag and If-None-Match and memory/disk cache 

### ISSUE THREAD

**Issue by neoneye** [Alamofire/AlamofireImage#111]
Greetings Christian Noon, it's a nice framework you have!

I want to use ETags. Where http-status 304 indicates that client has the newest data.
I have managed to made it work, but it's kludgy and seems wrong.

**Am I doing something wrong in my swift code?**

```swift
let url = NSURL(string: "http://example.com/thumbnail?json=JSON_HERE")

// Remove image from memory. This doesn't removes images from NSURLCache
let imageDownloader = imageView.af_imageDownloader ?? UIImageView.af_sharedImageDownloader
let imageCache: ImageRequestCache? = imageDownloader.imageCache
imageCache?.removeAllImagesForRequest(NSMutableURLRequest(URL: url))  // <----- is this wrong?

// Send If-None-Match to server with client data ETag
// If 304 then uses data from NSURLCache
// If 200 then uses data from server and saves it to NSURLCache
imageView.af_setImageWithURL(url)
```

### ETag Cache Miss

This is the request/response when the ETag is not up to date, and triggers the
server to generate a new thumbnail.

```
GET example.com/thumbnail?json=JSON_HERE HTTP/1.1
If-None-Match: "1463855136-531148"

----

HTTP/1.1 200 OK
Server: nginx/1.6.2
Date: Sat, 21 May 2016 18:25:52 GMT
Content-Type: image/jpg
Content-Length: 78070
Connection: keep-alive
ETag: "1463855147-637432"
Cache-Control: max-age=0

BINARY DATA HERE
```

### ETag Cache Hit

This is the request/response when the ETag is up to date. 
The server doesn't have to do anything.

```
GET example.com/thumbnail?json=JSON_HERE HTTP/1.1
If-None-Match: "1463855147-637432"

----

HTTP/1.1 304
Server: nginx/1.6.2
Date: Sat, 21 May 2016 18:25:53 GMT
Connection: keep-alive
```

**Comment by cnoon** [comment]
Hi @neoneye,

Apologies for not getting back to you sooner. In the case that you want to use an eTag, I'd suggest using the `NSURLRequest` variant on `af_setImageWithURL` so you can tack on the `If-None-Match` header with the eTag value. Then I'd also use the current image as a placeholder image. This would allow you to set the current image as the placeholder, then it will only replace the placeholder if you get a 200 back and not a 304. You could also tack on a cross-fade animation to switch between them.

Fully disclaimer, I haven't actually tried to do that, but I'm fairly confident that would all just work right out of the box. Then you wouldn't have to worry about clearing out the cache in any way.

Cheers. 🍻
