### ISSUE TITLE
ImageDownloader for video files

### ISSUE THREAD

**Issue by tfe** [Alamofire/AlamofireImage#113]
It would be great if all the cool features that ImageDownloader has (e.g. priority queue, caching, request receipts, request de-duplication) could be leveraged for downloading other types of files. In my specific case I have a lot of video content.

Love the project; great work!

**Comment by cnoon** [comment]
Thanks @tfe! I love your suggestion. I've actually built an internal library very similar to what you are mentioning (_I also have to deal with a lot of non-image specific data_). It does support all the mentioned features along with quite a few others. Let me think on this feature request and see what it could look like at the Alamofire level. I don't think it would make sense to put into AFI. 

Any thoughts on where this type of functionality should live?

**Comment by tfe** [comment]
Well, Alamofire would be a good place. I was kind of surprised it didn't have something like this already.

**Comment by TimWatson** [comment]
@cnoon Any update on this? I need something just like AlamofireImage but for videos.

**Comment by cnoon** [comment]
This is something that we're planning on adding in AF5. Timeline for that is roughly aligned with the Swift 4 official release.
