### ISSUE TITLE
Alamofire framework is NOT included in the Build Phases-> Copy Bundle Resources

### ISSUE THREAD

**Issue by MobileVet** [Alamofire/AlamofireImage#116]
As a result, if you manually add the AlamofireImage framework to your project, it will crash if you try and run it on a device.  (Simulator works fine)

Easiest work around is to add the Alamofire framework separately (adding the appropriate Build Phases references) and remove the references to Alamofire inside the Build Phases for AlamofireImage

**Comment by cnoon** [comment]
Hi @MobileVet, you need to make sure you add both the AlamofireImage and Alamofire framework to your app target when using submodules. For an example on how to set this up correctly, please have a look at the `iOS Example` app. That app is able to build onto a device without issue.

There's nothing here that I can see is an issue with AFI itself, but more of something that can trip you up when linking frameworks to app targets. I'm going to go ahead and close this issue out for now. If you have something specific in mind that you'd like to see improved in AFI in regards to this issue, please let me know and I'll be happy to re-open and investigate further.

Cheers. 🍻
