### ISSUE TITLE
Feature Request: ability to add GPS location data to EXIF header

### ISSUE THREAD

**Issue by isaac-oshima** [Alamofire/AlamofireImage#120]
ability to add GPS location data to EXIF header 
perhaps by CLLocation parameter or other...
Thanks for considering...

**Comment by cnoon** [comment]
Hi @isaac-oshima...thanks for taking the time to put together this suggestion! 

IMO, I don't think this type of functionality matches the current AFI feature set. We don't have any support right now for editing image metadata in any way. We only deal with raw pixel manipulation.

> With that said, if you feel strongly that this is something that belongs in AFI, we love pull requests and would certainly consider it!

Cheers. 🍻
