### ISSUE TITLE
Crash in ImageDownloader.swift

### ISSUE THREAD

**Issue by Maulik699** [Alamofire/AlamofireImage#122]
I am using `UITableView` with cell Image and want to set image with URL.
I am using `            cell.imgProcedure?.af_setImageWithURL(URL)
`
It crashed suddenly.You can see my console with crash [http://prntscr.com/biofqa](url)

Please fix this ASAP.

Thanks,
Maulik

**Comment by cnoon** [comment]
Hi @Maulik699,

Your link is dead and there's not enough info to go on. Most likely this is an issue with your app logic. We have many different tests ensuring the stability of that logic. With that said, it's always possible (however unlikely) that there is a problem in AFI. 

I'm going to close this issue out for now, but if you provide more info that leads us to believe there may be an actual AFI issue, we'll happily re-open and investigate further with you.

Cheers. 🍻
