### ISSUE TITLE
Error Domain=com.alamofire.error Code=-999

### ISSUE THREAD

**Issue by ivasic** [Alamofire/AlamofireImage#128]
When cancelling an image download (e.g. loading another image in an UIImageView while the previous request is still running), AlamofireImage executes the completion block with .Failure(error) like so:

    Error Domain=com.alamofire.error Code=-999 "ImageDownloader cancelled URL request: https://mywebsite/image.jpg" UserInfo={NSLocalizedFailureReason=ImageDownloader cancelled URL request: https://mywebsite/image.jpg}

Now this looks good but the error domain is set to alamofire (`com.alamofire.error`) and code -999 is not defined in this error domain but it seems that it is actually coming from `NSURLErrorDomain` and that would be code `NSURLErrorCancelled`. Shouldn't the domain really be `NSURLErrorDomain` rather than  `com.alamofire.error`?

**Comment by cnoon** [comment]
Thanks for reporting this @ivasic. You are completely right. The domain has been fixed in b2eb1005.

Cheers. 🍻
