### ISSUE TITLE
UIButton Extension

### ISSUE THREAD

**Issue by kingslay** [Alamofire/AlamofireImage#13]
Could you add support for `UIButton` `setImage` and `setBackgroundImage`?

**Comment by cnoon** [comment]
We'll add this to our Trello backlog. I'll also leave this issue open for others to +1 if they'd like to see it supported.

**Comment by markkrenek** [comment]
+1

**Comment by jgrandelli** [comment]
+1

**Comment by DimaVartanian** [comment]
+1

**Comment by CodeEagle** [comment]
+1

**Comment by PaulWoodIII** [comment]
+1

**Comment by aprigiovasconcelos** [comment]
+1

**Comment by yoshimikeisui** [comment]
+1

**Comment by Appsido** [comment]
+1

**Comment by cnoon** [comment]
I'm going to close this issue out. Please redirect all comments to #63. 👍🏼
