### ISSUE TITLE
making af_activeRequestReceipt public

### ISSUE THREAD

**Issue by JamieWhite** [Alamofire/AlamofireImage#139]
What do you think about the idea of making this public?

I think it would be useful to cancel off existing requests. Unlike Alamofire where you get a `Request` returned, AlamofireImage doesn't have any way of cancelling existing requests.

I considered the `af_setImageWithUrl` returning the receipt but it would just be easier to use the existing var.

Basically this is related to a problem I had a while ago where I had to skirt around AlamofireImage to cancel off a request if the image is too big (it was crashing my share extension). My solution is this:

```
request = Alamofire.request(.GET, url).responseImage(completionHandler: { [weak self] response in

                switch response.result {
                case .Success(let image):
                    self?.imageView.si_transitionImage(image)
                    completion(completed: true)
                case .Failure(let error):
                    completion(completed: false)
                }
            }).progress({ [weak self] _, _, totalExpected in
                if totalExpected > Int64(Image.maxImageSize) {
                    self?.request?.cancel()
                }
            })
```

With the new progress support on af_setImage I could do the same thing and leverage AlamofireImage to cancel off my request.

**Comment by cnoon** [comment]
Hi @JamieWhite,

You can already cancel an active image request using the [af_cancelImageRequest](https://github.com/Alamofire/AlamofireImage/blob/master/Source/UIImageView%2BAlamofireImage.swift#L338-L345) API. That should be everything you need.

Cheers. 🍻

**Comment by JamieWhite** [comment]
Hah. Sorry. RTFM
