### ISSUE TITLE
CocoaPods and Swift 2.3

### ISSUE THREAD

**Issue by picciano** [Alamofire/AlamofireImage#142]
What's the recommended approach for using the 2.3 branches with CocoaPods? Looks like the swift2.3 branch has a dependency on 3.3, but the swift2.3 branch of AlamfireImage is at 3.4.x.

```
Analyzing dependencies
Pre-downloading: `Alamofire` from `https://github.com/Alamofire/Alamofire.git`, branch `swift2.3`
Pre-downloading: `AlamofireImage` from `https://github.com/Alamofire/AlamofireImage.git`, branch `swift2.3`
[!] Unable to satisfy the following requirements:

- `Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `swift2.3`)` required by `Podfile`
- `Alamofire (~> 3.3)` required by `AlamofireImage (2.4.1)`
- `Alamofire (= 3.3.1)` required by `StarzServices (1.0.8)`
```

**Comment by cnoon** [comment]
You need to override both Alamofire and AlamofireImage in your Podfile to point at either the branches or commits you want.

```ruby
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift2.3'
pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git', :branch => 'swift2.3'
```

Cheers. 🍻

**Comment by dlo** [comment]
@cnoon The swift2.3 branches of both repos appear to have been deleted. Should we use the 2.5.0 tag instead?

**Comment by cnoon** [comment]
@dlo you want to use the AF 3.5.0 release for Swift 2.3 and the AF 4.0.0 release for Swift 3.

**Comment by dlo** [comment]
Great, thanks for clarifying. 👍
