### ISSUE TITLE
UIActivityIndicator show in UIImageView until image is downloaded from URL.

### ISSUE THREAD

**Issue by Rashesh-Bosamiya** [Alamofire/AlamofireImage#144]
I want to show UIActivityIndicator in UIImageView till image is downloaded from URL.

**Comment by cnoon** [comment]
This is something you can easily do on your own by adding the activity indicator to your image view, then using `af_setImage` to request the image. You can use the `completion` parameter to remove the activity indicator before the image is set.

Cheers. 🍻

**Comment by mirko77** [comment]
I have the same issue. The completion handler is called as soon as the view shows before the image gets downloaded.

```
 pintOriginalImage.af_setImage(
                withURL: url,
                placeholderImage: nil,
                filter: nil,
                imageTransition: .crossDissolve(0.2),
                completion : { response in
                    self.imageLoadingIndicator.stopAnimating() //called immediately??????
            })

```
