### ISSUE TITLE
Xcode 8 Beta 5 issue

### ISSUE THREAD

**Issue by Rishu** [Alamofire/AlamofireImage#145]
Unable to compile swift3 branch source on Xcode 8 Beta 5 Problems. Please let us know how can i compile it?

**Comment by cnoon** [comment]
We have not updated AFI for beta 5 yet. If you need to get it compiling, you'll need to do this on your own right now. Most likely we'll have this completed by the end of the week.

**Comment by Rishu** [comment]
@cnoon thanks for your information. I will try it.

**Comment by ivan-konov** [comment]
It seems to be working fine with beta 5 without the need for updates.
