### ISSUE TITLE
Feature request: Add subview rather than placeholder

### ISSUE THREAD

**Issue by farice** [Alamofire/AlamofireImage#147]
The af_setImageWithURL call is fantastic and I've integrated it deeply into my software, so thank you for the good work. However, I was curious if you have any plan to implement something along the lines of a placeholderSubview parameter? The placeholderImage parameter is a very nice touch. However, when one is seeking to download an image that will replace the one previously shown, it'd be ideal to overlay an image (or preferably animation) on the previous photo. This, however, may be too complicated to integrate. Thanks again for building a solid framework.

**Comment by cnoon** [comment]
This seems like a complicated enough use case that you'd probably just want to implement this yourself @farice. There are a few too many variables to make an elegant solution here that could satisfy everyone in AFI.

You should be able to leverage most of AFI though to make this a fairly straightforward feature to implement.

You can also use the `ImageTransition` enum to accomplish the animation portion of your request.

Cheers. 🍻
