### ISSUE TITLE
swift 3: Alamofire + AlamofireImage  error

### ISSUE THREAD

**Issue by freegor** [Alamofire/AlamofireImage#151]
Hi there,

I can't install pods - Alamofire and AlamofireImage in my project, it receive me an error: 
`- Alamofire (~> 3.3) required by `AlamofireImage (2.4.1)`
My podfile have: 
.......
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'swift3'
pod 'AlamofireImage', :git => 'https://github.com/Alamofire/AlamofireImage.git', :branch => 'swift3'
.......

Can you change  s.dependency 'Alamofire', '~> 3.3' to 'Alamofire', '~> 4.0' in AlamofireImage.podspec file of the swift3 branch?
( ['~> 0.1' Version 0.1 and the versions up to 1.0, not including 1.0 and higher.](https://guides.cocoapods.org/using/the-podfile.html))

Thank you.

**Comment by kemchenj** [comment]
And add Swift 3 **beta 6** support

**Comment by cnoon** [comment]
Hi @freegor, the podspec has been fixed in #154. @kemchenj, #154 also adds full support for beta 6. I'm going to go ahead and close this issue out. Please redirect all future comments to #154.

Cheers. 🍻
