### ISSUE TITLE
ImageCache always returns false when using removeImageWithIdentifier method.

### ISSUE THREAD

**Issue by asifbilal786** [Alamofire/AlamofireImage#152]
I am trying to remove the image from image cache using removeImageForRequest method of ImageCache. Although it performs the necessary work and delete the image from cache but it always returns false.

I think the issue is with dispatch_async_barrier block. Because the piece of code in it runs asynchronously hence it always return false.

Please fix this issue as it doesn't return true value when it has removed the image.

**Comment by cnoon** [comment]
Thanks for reporting @asifbilal786. It was definitely wrong. I've pushed a fix in 6be1da8b which is part of #154. I've also added tests to verify the return value now works as expected.

I'm going to close this issue out. Please redirect all further comments to #154.

**Comment by asifbilal786** [comment]
Thanks for quick fix. As i have implemented Pods, so did you also update the Cocoa Pods for this?

**Comment by cnoon** [comment]
The changes are still in review. Once we get it merged, we're going to release AF 4.0.0-beta.1 and AFI 3.0.0-beta.1. If you need to pull the changes in before, you can always point directly to the `beta6` branch in #154.
