### ISSUE TITLE
Dealing with MJPEG-Streams

### ISSUE THREAD

**Issue by ugoArangino** [Alamofire/AlamofireImage#156]
I have expanded #[AlamofireImage](https://github.com/ugoArangino/AlamofireImage) for dealing with #MJPEG-Streams

![Screenshot](https://pbs.twimg.com/media/Cqvo14mXgAAIp9c.jpg:large)

Heer is the link to my commit. https://github.com/ugoArangino/AlamofireImage/commit/5f2e952ccf242aa038e6bffbb91cc6d0bb9a1ecb

What do you think about this addition. Makes a pull request sense?
Or should I create a separate framework that provides a closure fur the streaming API.

**Comment by cnoon** [comment]
We're busy working through the AF 4 release right now @ugoArangino...I promise I'll dig in here and get you an answer soon. Please hang tight. 🍻

**Comment by robbiet480** [comment]
Updated this to the AF 4 changes and submitted a new PR at #185.

**Comment by cnoon** [comment]
Closing this out for #185. Please redirect all further comments to #185.

**Comment by rat-moonshine** [comment]
This is exact something I was looking for a support to MJPEG on tvOS. 

Is there any link/example codes available on this?

Thanks!

**Comment by ugoArangino** [comment]
@rat-moonshine This might help you https://github.com/ugoArangino/MJPEG-Framework

> This is exact something I was looking for a support to MJPEG on tvOS.
> 
> Is there any link/example codes available on this?
> 
> Thanks!

**Comment by rat-moonshine** [comment]
> @rat-moonshine This might help you https://github.com/ugoArangino/MJPEG-Framework
> 
> > This is exact something I was looking for a support to MJPEG on tvOS.
> > Is there any link/example codes available on this?
> > Thanks!

Hei thanks @ugoArangino ! Co-incidentally I have found another one https://github.com/WrathChaos/MJPEGStreamLib and this seems to be a more updated one too! Running good on Swift 5!
