### ISSUE TITLE
Add af_setImageWithURL for NSImageView

### ISSUE THREAD

**Issue by euskadi31** [Alamofire/AlamofireImage#157]
Hi,

Can you add `af_setImageWithURL` for `NSImageView` ? 

Thx

**Comment by cnoon** [comment]
The majority of the work has been completed in #107 if someone wants to complete the test suite for it. Would you be interested @euskadi31?

**Comment by cnoon** [comment]
I'm going to close this issue out. If someone wishes to add support for `NSImageView`, we'll gladly accept it with the appropriate unit tests. The majority of the work has already been completed in #107.
