### ISSUE TITLE
Swift3 error: Response<Image, NSError> != Response<Any>

### ISSUE THREAD

**Issue by arsonik** [Alamofire/AlamofireImage#158]
Is it just me ?
![screen shot 2016-08-30 at 12 07 13](https://cloud.githubusercontent.com/assets/1333734/18085190/5dec947a-6eaa-11e6-93bf-29ebc090c22a.png)

```
anImageView.af_setImage(withURL: url, placeholderImage: UIImage(named: "placeholder"))
```

error
```
dyld: lazy symbol binding failed: Symbol not found: __TFV9Alamofire18ResponseSerializerCfT17serializeResponseFTGSqV10Foundation10URLRequest_GSqCSo15HTTPURLResponse_GSqVS1_4Data_GSqCSo7NSError__GOS_6Resultxq___GS0_xq__
  Referenced from: ~/Library/Developer/CoreSimulator/Devices/46439747-EAFF-4EDF-A489-B63D59F023EF/data/Containers/Bundle/Application/5C746801-34A7-4ED0-9189-A39A1ED30F02/TV.app/Frameworks/AlamofireImage.framework/AlamofireImage
  Expected in: ~/Library/Developer/Xcode/DerivedData/xxx-ctideczydatvhffxnxhcuxarjxsq/Build/Products/Debug-appletvsimulator/Alamofire.framework/Alamofire
```

Using Xcode 8 beta 6, Carthage

**Comment by arsonik** [comment]
Ok I think the problem is that AlamofireImage is not yet compatible with the last Alamofire/swift3 branch.
https://github.com/Alamofire/Alamofire/blob/swift3/Source/Response.swift
```public struct Response<Value> {```
AlamofireImage is still using
https://github.com/Alamofire/AlamofireImage/blob/swift3/Source/ImageDownloader.swift
```
public class ImageDownloader {
    /// The completion handler closure used when an image download completes.
    public typealias CompletionHandler = (Response<Image, NSError>) -> Void ```

**Comment by cnoon** [comment]
This has all been resolved @arsonik with all the latest changes that just went into the AFI `swift3` branch. I'm going to go ahead and close this issue out.

Cheers. 🍻
