### ISSUE TITLE
Image is never set when af_setImageWithURL is called 2 times in a row

### ISSUE THREAD

**Issue by damienrambout** [Alamofire/AlamofireImage#17]
I've noticed that images are never set if I call `af_setImageWithURL` several times.
The following (test) code will always result in only the placeholder image being set.
```swift
imageView.af_setImageWithURL(imageURL, placeholderImage: placeholder, filter: AspectScaledToFillSizeFilter(size: imageView.bounds.size))
imageView.af_setImageWithURL(imageURL, placeholderImage: placeholder, filter: AspectScaledToFillSizeFilter(size: imageView.bounds.size))
```

The first request seems to be successfully cancelled (I get a cancelled error if I set the completion block).

Cheers.

**Comment by cnoon** [comment]
Thank you for reporting @damienrambout! This was certainly a bug. The logic was pretty obvious why the request was being cancelled. 

I reworked the main method a bit to ignore duplicate requests that match the active request in bc0e4fb6. I also added some tests around this behavior that fail without the patch and succeed with it. I'll push out a release here shortly with this fix.

Thanks again! 🍻

**Comment by dipang90** [comment]
I have use "af_setImageWithURL" but images is not loaded. Above problem is resolved? 
What is other way to fetch image from url using Alamofire in Swift? 

DIpang.
