### ISSUE TITLE
Doesn't build on Xcode 8 GM

### ISSUE THREAD

**Issue by tsheaff** [Alamofire/AlamofireImage#171]
I get a single error when building with Xcode 8 GM on latest swift3 branch

![screen shot 2016-09-07 at 3 26 10 pm](https://cloud.githubusercontent.com/assets/1238684/18330788/792b6d68-750f-11e6-86ac-9a380892eaf9.png)

`Cannot call value of non-functional type HTTPURLResponse?` @cnoon

**Comment by cnoon** [comment]
Everything has been resolved @tsheaff. We've just released Alamofire 4 and AlamofireImage 3. Both are tagged and the podspecs are available. I've also deleted the `swift3` branch entirely. Please let us know if you have issues from here on out.

Cheers. 🍻
