### ISSUE TITLE
Alamofire PR #1491 breaks AlamofireImage

### ISSUE THREAD

**Issue by kaarelkivistik** [Alamofire/AlamofireImage#174]
See this: [https://github.com/Alamofire/Alamofire/pull/1491](url).

Workaround for now is to use an earlier commit:
`pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire', :commit => '76558cf44275cc6a6b9ebee9e3ac53b281d504b2'`

**Comment by cnoon** [comment]
Everything has been fixed up now @kaarelkivistik...we've just released Alamofire 4 and AlamofireImage 3 officially.

Cheers. 🍻
