### ISSUE TITLE
3.0.0 installed via Pod: 626 build errors

### ISSUE THREAD

**Issue by Jiropole** [Alamofire/AlamofireImage#179]
I get a massive stack of build errors after installing AlamofireImage via my podfile (`pod 'AlamofireImage', '~> 3.0'`), regardless of target device. This is on a modern Swift project targeting iOS9, with no other errors; XCode 7.3.1 (7D1014). The errors are nearly all related to conflicting or missing definitions. While I do not directly rely on other AF libraries, other pods do. Related libraries:
```
Using AFNetworking (3.1.0)
Using Alamofire (4.0.0)
Using AlamofireImage (3.0.0)
```

**Comment by jshier** [comment]
Alamofire 4 is Swift 3 and therefore incompatible with Xcode 7.

**Comment by Jiropole** [comment]
So... can't be used with the production version of XCode? Now that's bleeding edge. Is there a different version of AlamofireImage you recommend, or would it be best to look for another solution altogether.

**Comment by jshier** [comment]
The Xcode 8 GM is out now. If you want to keep using Xcode 7, use Alamofire 2.x, like our README recommends.

**Comment by Jiropole** [comment]
I don't see that in the README, but I should have read the 3.0 requirements more carefully. Thanks.

**Comment by jshier** [comment]
Sorry, it was in our [migration guide](https://github.com/Alamofire/AlamofireImage/blob/master/Documentation/AlamofireImage%203.0%20Migration%20Guide.md).
