### ISSUE TITLE
Cannot load images from file URL

### ISSUE THREAD

**Issue by alexanderedge** [Alamofire/AlamofireImage#18]
Hi there,

Firstly, fantastic work so far, I'm really looking forward to working with AlamofireImage and contributing where I can.

I've noticed that loading from an image file to a `UIImageView` from the application bundle (and, presumably, a location on disk) doesn't work. I haven't yet had time to look into why, but I thought I should bring it to your attention.

An example file URL:

```
file:///Users/alexanderedge/Library/Developer/CoreSimulator/Devices/B0CBC833-1F6C-4099-9B19-258DFE22AC89/data/Containers/Bundle/Application/388B99E5-E443-4C87-A22B-EB41BC192044/MyApp.app/image_06.1.png
```

An example call:

```
imageView.af_setImageWithURL(NSBundle.mainBundle().URLForResource(name: "image_06.1", withExtension: "png"))
```

**Comment by cnoon** [comment]
Ah sorry about that. AlamofireImage does not support file URLs. It's only designed to work with remote images. At the moment I don't think that I want to extend AlamofireImage to support this case. I'm afraid it would just be too confusing for users.
