### ISSUE TITLE
How does AlamofireImage support animated GIFs?

### ISSUE THREAD

**Issue by bdrelling** [Alamofire/AlamofireImage#182]
I am currently using Kingfisher and hoping to switch to AlamofireImage since I use your other libraries very extensively and love the work. However, Kingfisher has specific solutions for animated GIFs and I don't see any info for it on the doc for AlamofireImage. Is that because there's nothing different I'd need to do?

**Comment by jshier** [comment]
Could you be more specific? AlamofireImage is just an image downloading a caching library, nothing more. It provides no special support for any one format.

**Comment by cnoon** [comment]
There is no direct support for animated GIFs at this time @bdrelling. It's in our Trello backlog but is not currently one of our higher priorities.

Cheers. 🍻
