### ISSUE TITLE
 Cannot call value of non-function type 'HTTPURLResponse?'

### ISSUE THREAD

**Issue by illyaBakurov** [Alamofire/AlamofireImage#183]
Is it just me? After updating to Alamofire 4.0.0 and AlamofireImage 3.0.0 I am receiving this error in AlamofireImage:

 Cannot call value of non-function type 'HTTPURLResponse?' in Request + AlamofireImage.swift on line 126:

 @discardableResult
    public func responseImage(
        _ imageScale: CGFloat = DataRequest.imageScale,
        inflateResponseImage: Bool = true,
        completionHandler: @escaping (DataResponse<Image>) -> Void)
        -> Self
    {
 126 -        return response(
            responseSerializer: DataRequest.imageResponseSerializer(
                imageScale: imageScale,
                inflateResponseImage: inflateResponseImage
            ),
            completionHandler: completionHandler
        )
    }

Any suggestions how to resolve the issue? Or what am I missing?

**Comment by illyaBakurov** [comment]
**UPD:**

Resolved the issue by removing 'imageScale' on 128 line as a variable name.

That's what working return looks like:

return response(responseSerializer: DataRequest.imageResponseSerializer(imageScale, inflateResponseImage: inflateResponseImage), completionHandler: completionHandler)

**Comment by jshier** [comment]
Please ensure you're using the release versions of Alamofire and AlamofireImage, as both should build without error using Xcode 8.

**Comment by skrenek** [comment]
I just had to make the same change the @illyaBakurov mentioned to get it to compile.  This is in AlamofireImage 3.1.0 installed via Cocoapods 1.1.1.  Removing the imageScale parameter name worked for me.
