### ISSUE TITLE
 Error in alamofire - 4.0 ( 3.0 swift )

### ISSUE THREAD

**Issue by dev12-SC** [Alamofire/AlamofireImage#186]
I'm a mistake to use the alamofire in xcode 8.0 with 3.0 swift .
I tried many ways to work , updated in the pod lib alamofire to 4.0 the last came out with swift supports 3.0 and I'm in trouble .
Problem is in the picture below , if someone can help me with this problem thanks
![erro alamofire](https://cloud.githubusercontent.com/assets/15039214/18648412/e4628fc8-7e90-11e6-8353-7d92734348f3.jpg)

Help me please!

**Comment by jimsmithm3** [comment]
For what's it's worth I am running into this exact issue myself today with 4.0.0 and 3.0.0

**Comment by michael-mckenna** [comment]
I have the exact same issue

**Comment by jamshaidsadiq** [comment]
I have the exact same issue
<img width="798" alt="screen shot 2016-09-20 at 12 25 34 pm" src="https://cloud.githubusercontent.com/assets/17274199/18661905/588303f6-7f31-11e6-8542-34a4aefd8a53.png">

**Comment by AlbertoMrFz** [comment]
I have the exact same issue

Any solutions??

**Comment by MathisDetourbet** [comment]
Same for me too ! Need help :)

**Comment by appsailor** [comment]
change to following line and it fixes the compilation issue: 

return response(responseSerializer: DataRequest.imageResponseSerializer**(imageScale, inflateResponseImage: inflateResponseImage)**, completionHandler: completionHandler)

**Comment by MathisDetourbet** [comment]
Thanks @appsailor ! :)

**Comment by guycassidy** [comment]
@appsailor fix works for me! Thanks!

**Comment by CLutas** [comment]
@appsailor thx, that fixed it 👍

**Comment by dev12-SC** [comment]
[SOLVED] do it every lib that you are having this problem, and this solves the problem
before:
![do before](https://cloud.githubusercontent.com/assets/15039214/18964887/b35b7524-862f-11e6-8a1c-15334c7bd957.png)
after:
![to after](https://cloud.githubusercontent.com/assets/15039214/18964888/b38658ac-862f-11e6-8762-590bc803051a.png)

**Comment by cnoon** [comment]
I'm going to close this out. Thanks everyone for helping out! 🍻

**Comment by scottrichards** [comment]
Thanks Appsailor you saved me!
