### ISSUE TITLE
Cannot call value of non-function type 'NSHTTPURLResponse?'

### ISSUE THREAD

**Issue by guycassidy** [Alamofire/AlamofireImage#188]
I'm getting this error when trying to compile after migrating from 2.3 to swift 3. 

This is pointing to Request+AlamofireImage.swift
<img width="657" alt="screen shot 2016-09-22 at 16 16 59" src="https://cloud.githubusercontent.com/assets/2297907/18754286/09b06b96-80e0-11e6-8b85-1cff8f53eacf.png">

Any idea why this is happening? It looks like I got the latest code from AlamoFire (version 4) and AlamofireImage (version 3)

**Comment by hanappaula** [comment]
Also happening here when trying to compile after migrating from 2.3 to swift 3.

**Comment by hanappaula** [comment]
Duplicated issue #186

**Comment by cnoon** [comment]
Make sure you installed using the latest CocoaPods or Carthage.
