### ISSUE TITLE
Blur Filter typo in docs

### ISSUE THREAD

**Issue by btelintelo** [Alamofire/AlamofireImage#189]
let blurredImage = image.af_imageFiltered(
    withCoreImageFilter: "CIGuassianBlue",
    parameters: ["inputRadius": 25]
)

^Should say "CIGaussianBlur" not "CIGuassianBlue"

**Comment by cnoon** [comment]
Thanks @btelintelo...fixed in 609f6251. 

Cheers. 🍻
