### ISSUE TITLE
Response Validation failure for Image download

### ISSUE THREAD

**Issue by abyt07** [Alamofire/AlamofireImage#190]
When downloading image from URL of Huffington post: (http://img.huffingtonpost.com/asset/74_58/57e5a0151b00002e00ef1c6e.jpg), shows Response Validation failed. Installed the latest version of AlamofireImage through Cocoapods
`pod 'AlamofireImage'`

Please find the error details below:
FAILURE: 

> responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.unacceptableContentType(["image/tiff", "image/x-win-bitmap", "image/jpeg", "image/x-icon", "image/ico", "image/gif", "image/bmp", "image/x-bmp", "image/x-xbitmap", "image/png", "image/x-ms-bmp"], "image/jpg"))
>   ▿ failure : AFError
>     ▿ responseValidationFailed : ResponseValidationFailureReason
>       ▿ unacceptableContentType : 2 elements
>         ▿ .0 : 11 elements
>           - 0 : "image/tiff"
>           - 1 : "image/x-win-bitmap"
>           - 2 : "image/jpeg"
>           - 3 : "image/x-icon"
>           - 4 : "image/ico"
>           - 5 : "image/gif"
>           - 6 : "image/bmp"
>           - 7 : "image/x-bmp"
>           - 8 : "image/x-xbitmap"
>           - 9 : "image/png"
>           - 10 : "image/x-ms-bmp"
>         - .1 : "image/jpg"

**Comment by cnoon** [comment]
Hi @abyt07,

The `Content-Type` returned from that request is not an accepted content type. In order to support it, you need to add it to the list of acceptable content types. That can be done like so:

```swift
DataRequest.addAcceptableImageContentTypes(["image/jpg"])

let urlString = "http://img.huffingtonpost.com/asset/74_58/57e5a0151b00002e00ef1c6e.jpg"

Alamofire.request(urlString).responseImage { response in
    debugPrint(response)
}
```

Cheers. 🍻

**Comment by venkatchm** [comment]
How do I download pdf image?
