### ISSUE TITLE
Using ImageFilter on local image resource blocks the UI

### ISSUE THREAD

**Issue by AmineG** [Alamofire/AlamofireImage#191]
I am using ImageFilter on downloaded images, and I want to use it also for the placeholder that is using a local image resource.
The problem that I am facing is that once I apply the filter on a local file, it blocks the UI.
Below is the code snippets I am using : 
```
var filter:ImageFilter = BlurFilter(blurRadius:3)
var placeHolderImage = filter?.filter(UIImage(named:"my-local-image-name")!)

```

I am setting filtered images for a list of elements, and this behaviour causes now an important delay  when I open the view containing these filtered images.
Are you planning to enhance this behaviour ?
Should I do the images filtering in a delayed block ?

**Comment by cnoon** [comment]
The placeholder image does NOT support filtering. It needs to be fully constructed and ready to go before using the `af_setImage` APIs. In this case, you'll want to filter the image first. When complete, then you can use it with the `af_setImage` APIs.

Cheers. 🍻
