### ISSUE TITLE
BlurFilter causes a reduction in the image size

### ISSUE THREAD

**Issue by AmineG** [Alamofire/AlamofireImage#192]
I am using BlurFilter filter to make the blur effect on images received from the server.

I noticed that when I apply the filter, the image content become slightly smaller, and I have more blank spaces near borders.

Here is the used filter: 
`var filter:ImageFilter = BlurFilter(blurRadius:3)`

**Comment by cnoon** [comment]
This is what happens when using CoreImage blur filters. If you need a different behavior, you can use a scale filter afterwards to update the size, or write your own blur filter implementation.

Cheers. 🍻
