### ISSUE TITLE
Feature Request: Support progressive JPEG file type

### ISSUE THREAD

**Issue by speedy99** [Alamofire/AlamofireImage#193]
I am serving images from AWS S3, the following mime-type is not supported out of the box for AlamofireImage (2.4.1):
`image/pjpeg`
I am using af_setImageWithURL() with a single NSURL argument. 
I am currently using the workaround:
`Alamofire.Request.addAcceptableImageContentTypes(["image/pjpeg"])`
(which works fine for me)
I could not tell how standard the pjpeg MIME type is. If nonstandard, please close this request.

**Comment by cnoon** [comment]
Hi @speedy99,

AFI currently does not have any direct support for progressive JPEGs. I've added it to our Trello backlog, but it's not high on our priority list. 

Adding the `image/pjpeg` content type to the list of acceptable content types is what you should do for now. Please keep in mind though that this will not actually perform any progressive rendering. It will just load all the data into a UIImage. If you need progressive display, then I'd recommend checking out something like [Concorde](https://github.com/contentful-labs/Concorde).

Cheers. 🍻

**Comment by asad-khan92** [comment]
Hi @cnoon any update on this?

**Comment by cnoon** [comment]
None yet @asad-khan92. All efforts now are being put towards the final release of AF5.

**Comment by asad-khan92** [comment]
@cnoon Ok, thanks for the reply.
