### ISSUE TITLE
Cannot call value of non function type 'Httpurlresponse'

### ISSUE THREAD

**Issue by Derrick250** [Alamofire/AlamofireImage#195]
I just upgrade to swift 3 and xcode 8 and the Request+alamofireImage.swift throws the above error on line 126. Just to add I'm new to swift and ios development

**Comment by cnoon** [comment]
Please see https://github.com/Alamofire/AlamofireImage/issues/188. You need to make sure to use CocoaPods 1.1.0-rc.2 or the latest version of Carthage when you install AFI 3.

Cheers. 🍻
