### ISSUE TITLE
Cannot call value of non-function type 'HTTPURLResponse?'

### ISSUE THREAD

**Issue by durul** [Alamofire/AlamofireImage#198]
I am taking error from " imageRequest.request.response(queue: queue... " ? Do you have any idea.

    //MARK: - Image Downloading
    
    func getNetworkImage(urlString: String, completion: @escaping ((UIImage) -> Void)) -> (ImageRequest) {
        let queue = decoder.queue.underlyingQueue
        let request = Alamofire.request(urlString)
        let imageRequest = ImageRequest(request: request)
        
        imageRequest.request.response(queue: queue,
            responseSerializer: Request.imageResponseSerializer(),
            completionHandler: { response in
                guard let image = response.result.value else {
                    return
                }
                let decodeOperation = self.decodeImage(image) { image in
                    completion(image)
                    self.cacheImage(image, urlString: urlString)
                }
                imageRequest.decodeOperation = decodeOperation
            }
        )
        return imageRequest
    }

**Comment by jshier** [comment]
You need to use `DataRequest.imageResponseSerializer()`.

**Comment by durul** [comment]
Thank you.
