### ISSUE TITLE
Framework not safe for use in app extensions

### ISSUE THREAD

**Issue by mattdelves** [Alamofire/AlamofireImage#2]
I'm looking at using AlamofireImage in an app that I'm building though when I link against it in an application extension I get the warning "Linking against dylib not safe for use in application extensions".

Is that something which has been done on purpose?

Happy to provide a pull request if required.

Thanks,
Matt.

**Comment by cnoon** [comment]
It was definitely not done on purpose. A pull request would be great if you could put that together!

**Comment by cnoon** [comment]
Thanks for your PR in #4 @mattdelves. I'm going to close this issue out.
