### ISSUE TITLE
Hard to change ImageDownloader's DownloadPrioritization

### ISSUE THREAD

**Issue by graham-perks-snap** [Alamofire/AlamofireImage#200]
DownloadPrioritization can be fifo or lifo.

The default ImageDownloader is fifo and can't be changed (downloadPrioritization is a `let`). For some apps (like mine I suspect!), lifo would be a better scenario.

There isn't a way to get a lifo queue, other than creating a new ImageDownloader instance. But that can be quite heavy handed.

Can downloadPrioritization be changed to `var`?

**Comment by graham-perks-snap** [comment]
A different option which would help in my case would be keep the FIFO behavior, but let me add images to the back of the queue. (a `downloadPrioritization` option on `download`?)

I am trying to get the cache warmed up by downloading images ahead of time; but I want these downloads to be lower priority, as the user can reach a point where I need to show them images ASAP.

**Comment by cnoon** [comment]
Hi @graham-perks-snap,

You can't change the download prioritization safely once you've made an `ImageDownloader`, especially once you've started adding things to the queue. So we (and you) don't really want to change that.

Instead, just make a new `ImageDownloader` instance. You say it's "heavy-handed", but did you actually try? It's literally as simple as this:

```swift
let downloader = ImageDownloader(downloadPrioritization: .lifo)
```

Seems pretty straightforward to me. That's what I would recommend you do.

Cheers. 🍻

**Comment by graham-perks-snap** [comment]
Doesn't that create a new cache? And if I use both image downloaders, another set of parallel `maximumActiveDownloads`, and no prioritization between the two queues?

I can't see how how altering `downloadPrioritization` is unsafe. It's only read in one method, `enqueue`, with no threading issues on that read.
