### ISSUE TITLE
Storage folder (Path)

### ISSUE THREAD

**Issue by hirenpanchal1608** [Alamofire/AlamofireImage#205]
I want to create my own folder and store images into this newly created folder.
Can i do this.?
If yes then how.?

**Comment by cnoon** [comment]
Hi @hirenpanchal1608,

Currently, AFI uses the system `URLCache` to save all image data to disk and respects all the HTTP headers associated with the image data. There's a very in-depth discussion on this topic in #5.

If you wish to ignore the HTTP headers and control the entire caching system, then you could disable the `URLCache` and build your own on-disk persistence cache by conforming to the `ImageRequestCache` protocol and setting your new cache class on the `ImageDownloader`. That would make you responsible though for handling all the on-disk purging. You can certainly use the `AutoPurgingImageCache` as an example, but it's only an in-memory cache.

Best of luck! 🍻
