### ISSUE TITLE
Support for animated gifs

### ISSUE THREAD

**Issue by tapz** [Alamofire/AlamofireImage#206]
Should get the frames from the gif data with CGImageSourceCreateImageAtIndex and create and animated image with UIImage.animatedImage. See https://github.com/zalando/MapleBacon/blob/master/Library/MapleBacon/MapleBacon/ImageGifExtension.swift

Currently there is not even a way to get the downloaded image data and do this myself.  Would be nice to have the image bytes too in the completion handler. No need for them if the image comes from the cache (not sure if the downloaded data is currently saved to the disk cache without first converting it to UIImage and losing the animated information).

**Comment by cnoon** [comment]
Hi @tapz,

With your changes merged in #208, you should now be able to add GIF support using your own custom image serializer. I've also bumped up the priority here in our Trello backlog to add GIF support directly into AFI in our 3.3 release. Stay tuned.

Cheers. 🍻

**Comment by Jiropole** [comment]
Would you have any links for building GIF support? I did see [this](https://littlebitesofcocoa.com/94-custom-alamofire-response-serializers) for general response serializers, which helps point the way. Else, any idea when we can look forward to v3.3/gif support (so cool)?
