### ISSUE TITLE
ImageDownloader caching problem

### ISSUE THREAD

**Issue by danieldelouya** [Alamofire/AlamofireImage#212]
In my app i start downloading a bunch of images using UIImageView.af_sharedImageDownloader.download(). 

Once it has downloaded all the images I set each image via myImageView.af_setImage, but it does not recognize them as cached, and downloads each image. 

When I restart the app, it has successfully cached the images and they appear instantly. 

Seems like a bug? Help please.

**Comment by chenawu2** [comment]
Same issue here.

**Comment by danieldelouya** [comment]
@chenawu2 Briefly gave Kingfisher a try, and their prefetched works flawlessly. Would love to hear from the Alamofire guys if there is a solution to this.

**Comment by pomarec** [comment]
Here is an idea : put a breakpoint line 197 in ImageCache.swift
My guess is that the cache is purged because you download images that are too big for the memory (it's not a disk backed cache)

**Comment by cnoon** [comment]
I tend to agree with @pomarec here @danieldelouya. We have MANY tests around this behavior that verify everything in the caching logic works correctly. I just dropped print statements into the example app in the `af_setImage` implementation to verify and it also works exactly as expected.

How do you know the caching isn't working? What are your cache settings? Could you provide a sample app demonstrating the issue?

I'm almost positive this is a cache configuration issue as @pomarec alluded to. My guess is that either your cache sizes are set incorrectly or you've disabled the `URLCache` or the in-memory cache. If you could post up a sample app demonstrating the problem, we'd be happy to investigate. But all our tests and our sample app point to this working exactly as expected.

I'm going to close this issue out for now. If you can post up a sample app, I'll happily re-open and help investigate further.

Cheers. 🍻
