### ISSUE TITLE
Restore iOS 8 compatibility

### ISSUE THREAD

**Issue by ejeklint** [Alamofire/AlamofireImage#216]
Now that Alamofire reinstates iOS 8 compatibility with release 4.1, it would be great if AlamofireImage would do so as well. Swift 2.3 will be deprecated faster than iOS 8 will disappear.

**Comment by codytwinton** [comment]
@ejeklint +1 to this

**Comment by codytwinton** [comment]
I've created a Pull Request to that effect

#217

**Comment by codytwinton** [comment]
#217

**Comment by ejeklint** [comment]
Thanks! :party:

**Comment by cnoon** [comment]
This has been completed in e0c2cf12. It will be released shortly.

Cheers. 🍻
