### ISSUE TITLE
image encryption

### ISSUE THREAD

**Issue by tranvutuan** [Alamofire/AlamofireImage#219]
I have a question regarding to the security issue. Can cached images be encrypted ?

**Comment by cnoon** [comment]
Well, the entire in-memory caching system is built around the `UIImage` and `NSImage` APIs. If your encrypted data can be converted into either of those types, then you can certainly store them in the in-memory cache.

The data will automatically be stored in its original encrypted form in the `URLCache`. However, there's no decryption logic built into any of the Alamofire image response serializers, so you'd need to implement this on your own.

Hopefully that answers your question.

Cheers. 🍻
