### ISSUE TITLE
Support for vector images pdf

### ISSUE THREAD

**Issue by Pacana78** [Alamofire/AlamofireImage#220]
Hi,
I'm trying to download from the server pdf vector images for an iOS project. Even if I've added DataRequest.addAcceptableImageContentTypes(["application/pdf"]) before the request the application throw a AFIError.imageSerializationFailed when tries to serialise the image itself.

Is there any way I can download vector pdf images with AlamofireImage?

Many thanks,
Simona

**Comment by Pacana78** [comment]
@cnoon  could you please help me on this, I'm kind of stuck :(

**Comment by jshier** [comment]
Unfortunately `UIImage` doesn't natively support PDF content and therefore can't be used automatically by AlamofireImage. We'll investigate how we can add such support.

**Comment by nverinaud** [comment]
SVG support would also be great !

**Comment by ArkadiGiniApps** [comment]
Something doesn't add up you can use PDF assets in the app bundle and load them with uiimage(named:) constructor so you should be able to do the same with files you download from the web.

**Comment by cnoon** [comment]
You cannot @ArkadiGiniApps. The PDF assets are converted as part of the asset catalog build process. That is what @jshier is referring to. @Pacana78 there is no way to do this currently in AlamofireImage. I've added it to our backlog and we'll consider it for upcoming releases.

Cheers. 🍻

**Comment by Pacana78** [comment]
Thanks @cnoon I hope you'll support it soon

**Comment by ivangodfather** [comment]
any updates on this?

**Comment by luan-sala** [comment]
https://www.hackingwithswift.com/example-code/core-graphics/how-to-render-a-pdf-to-an-image
this help?

**Comment by MarekSlaninka** [comment]
Ok, Im sorry, its working now and could update SwiftLint to new version. Thank You and sorry again
