### ISSUE TITLE
Ecapsulation of AlamofireImage

### ISSUE THREAD

**Issue by ogezue** [Alamofire/AlamofireImage#228]
I try to put the loading of images into my model so that my controller doesn't need to know anything about external libraries.

For this I wrote this method in my model that loads the image if I'm online. 

```
func loadImageWithUrl(url: String, successHandler: @escaping (UIImage) -> (), errorHandler: @escaping () -> ()){

        imageDownloader.addAuthentication(user: userID, password: password)
        
        let urlRequest = URLRequest(url: URL(string: url)!)
        
        imageDownloader.download(urlRequest) { response in
           
            if let image = response.result.value {
                successHandler(image)
            }
            else {
                if let image = self.imageDownloader.imageCache?.image(for: urlRequest, withIdentifier: nil) {
                    successHandler(image)
                } else {
                    errorHandler()
                }
            }
        }
    }
```

I also try to load the cached image from disk if the download fails. But the image could not be found even if it was loaded before I went offline. Any ideas how to fix this?

**Comment by cnoon** [comment]
Hi @ogezue,

The `imageDownloader` will automatically look for your image in the image cache by default. If it's in there, it won't hit the network to fetch the image, it will pull if directly from the cache. The check you're doing to fetch the image from the cache is not necessary.

On a slightly different note, why don't you just use the `UIImageView` extension to set the image. That's exactly what it's designed for. If you need to add the authentication, you can do so by using the `UIImageView.af_sharedImageDownloader` property.

Best of luck! 🍻
