### ISSUE TITLE
2 phase image download 

### ISSUE THREAD

**Issue by Lweek** [Alamofire/AlamofireImage#23]
Hi, I have an idea for feature.

Some content driven apps use two phase image download. It download super small image preview first and then it request large full res image.

So the flow is:
1. show placeholder image
2. show blurred low res preview (is purged from memory as soon as full res is available)
3. show cached full res image

Low res previews have slightly higher priority for download queue.

It would be super nice to have such feature build right in ImageDownloader.

Cheers and best wishes, Vlad

**Comment by cnoon** [comment]
Would you expect it to actually take two URLs in the `UIImageView` extension? One for the low res image and one for the higher res?

**Comment by Lweek** [comment]
@cnoon Yes please. That's reasonable because URLs might differ. Also an option parameter for low res thumbnail image filter would be nice.

**Comment by cnoon** [comment]
Thanks for the feedback here @Lweek. The low res thumbnail image filter support already exists. However, the ability to use a placeholder, then download a low res thumbnail, then download the full res image is an interesting idea. 

I'm going to leave this issue open for a few weeks to allow others in the community to comment or +1.

**Comment by huynhphan89** [comment]
+1

**Comment by mpantiru** [comment]
+1

**Comment by Kakahn** [comment]
+1

**Comment by jgrandelli** [comment]
+1

**Comment by iTSangarDEV** [comment]
+1

**Comment by amorenew** [comment]
i make holder then download 
 cell.vehicleImageView.image = UIImage(named: "missed_car")

let vehicleImageUrl = dealVehicleImages[indexPath.row]
        
   Alamofire.request(.GET, vehicleImageUrl)
            .responseImage { response in
                if let image = response.result.value {
                    cell.vehicleImageView.image = image
                }

**Comment by kean** [comment]
This feature seems to be very application-specific.

**Comment by cnoon** [comment]
Okay everyone, I've been pondering whether to support this feature request for the past few weeks and I've finally decided that this doesn't belong in AFI. It's just too specific of a use case and has some tradeoffs in implementation that would really complicate things. If you need this type of functionality, you'll need to roll your own implementation using a combination of the `af_setImageWithURL` chained methods.

Cheers.
