### ISSUE TITLE
how I can send header with alamofire image

### ISSUE THREAD

**Issue by ahmedsafadii** [Alamofire/AlamofireImage#231]
```
let imageView = UIImageView(frame: frame)
let url = URL(string: "https://httpbin.org/image/png")!
let placeholderImage = UIImage(named: "placeholder")!

imageView.af_setImage(withURL: url, placeholderImage: placeholderImage)


```

how I can send header in URL

```
var urlRequest = URLRequest(url: URL(string: "url")!)
urlRequest.setValue("my header", forHTTPHeaderField: "User-Agent")

```

**Comment by edgarplazola** [comment]
hi my friend i have the same problem and i solved it with this code

let headers = ["Authorization": "Bearer \(token)"]
let imageURL = try! URLRequest(url: gsUtil.getCompleteURI()+"image/"+usrId+".jpg", method: .get, headers: headers)

**Comment by cnoon** [comment]
Thanks @edgarplazola! As @edgarplazola mentioned @ahmedsafadii, you will need to construct a `URLRequest` in order to send custom headers along with your request.

```swift
var urlRequest = URLRequest(url: URL(string: "url")!)
urlRequest.setValue("my header", forHTTPHeaderField: "User-Agent")

imageView.af_setImage(urlRequest)
```

Best of luck! 🍻

**Comment by ahmedsafadii** [comment]
Cannot convert value of type 'URLRequest' to expected argument type 'URL'

        var urlRequest = URLRequest(url: URL(string: "https://api.lolsummoners.headlezz.net/images/champions/splashs/Taric0.jpg")!)
        urlRequest.setValue("my header", forHTTPHeaderField: "User-Agent")
        championSplash.af_setImage(withURL: urlRequest, placeholderImage: UIImage(named: "noimage"))

**Comment by RolandasRazma** [comment]
@ahmedsafadii it's `af_setImage(withURLRequest: ...`

**Comment by liwonder** [comment]
Hi @cnoon, I know this is closed, but I still want to say that the `af_setImage(withURLRequest: ...` method is tedious，as we have write it everywhere. Do we have any chance to add a custom method to replace the method below for extra header field such as authorization token。


    private func urlRequest(with url: URL) -> URLRequest {
        var urlRequest = URLRequest(url: url)

        for mimeType in DataRequest.acceptableImageContentTypes {
            urlRequest.addValue(mimeType, forHTTPHeaderField: "Accept")
        }

        return urlRequest
    }`
