### ISSUE TITLE
Download cancellation issue on bad network and a lot of download tasks

### ISSUE THREAD

**Issue by seart13** [Alamofire/AlamofireImage#232]
I have a `UICollectionView`-based app which loads a lot of images using `AlamofireImage`. I've noticed image loading performance degradation on bad network connection especially during collection view scroll. To illustrate this I've setup a [sample project](https://github.com/seart13/AlamofireImageDownloadCancellation). I call `af_setImage(withURL:placeholderImage:filter:progress:progressQueue:imageTransition:runImageTransitionIfCached:completion:)` method with non-nil progress handler. In progress handler I set the background color of the image view with alpha proportional to download progress, so when the download is started the color is transparent and as download completes the background saturates to complete opaqueness. Also (and this is the critical part of the issue) I cancel current image download in `prepareForReuse()` method.

If you launch the app you can see that images download as you would expect: green background appears, it saturates pretty quickly and then the image appears.

But if you launch the app, scroll the collection view to the bottom and stop scrolling you will notice that green background on each image view blinks a lot. This means that each image view has a lot of image downloads in-progress that change it's background via progress handlers.

The described behavior is due to the following condition in `ImageDownloader.cancelRequest(requestReceipt:)`:
```
if responseHandler.operations.isEmpty && requestReceipt.request.task?.state == .suspended {
    requestReceipt.request.cancel()
    self.responseHandlers.removeValue(forKey: urlID)
}
```

This means that `AlamofireImag` cancels `URLSessionTask` only if it has not started already. And this behavior is pretty unexpected to me. Not only the name of the method lies about actual behavior of the method, but also this leads to cluttering up the download queue. And that leads to even worse download performance than it could be on a bad network.

I beleive that `AlamofireImage` is doing so for optimizations: once the download have started it will be finished, the image will be cached so it will be immediately available when we scroll to the top. But this behavior of fake cancellation is totally undesirable for certain types of apps and for certain conditions: e.g. apps with non-static feeds and slow internet connection (or even a 3G). But we have no control over the described behavior in the current API.

Right now I fixed the issue by removing the state check of the task, but I decided to ask for oppinion of the community on the situation before doing a pull request. I understand that my fix will break the default behavior of other apps that expect `AlamofireImage` to finish download and cache the image once the download has been started. But I also would like to address the issue.

Probably the simplest solution I can think of is to add a bool flag called `forced` to the `ImageView.af_cancelImageRequest()` method to be able to actually stop the underlying `URLSessionTask` no matter what. Do you think that would be possible or will it break some inner invariants inside `AlamofireImage`?

Also request prioritization comes to mind, but I recon that it would be extremely difficult to implement correctly as it includes not only multithreaded code, but also stuff like dynamic priority changing, priority inversion etc.

Any help would be much appreciated!

**Comment by Flaww** [comment]
I have the same problem. A large infinite collection of images, combined with a weak connection and fast scrolling, you have to wait a long time before appears new products picture. As for me, your solution with the flag of "force" would be sufficient, thanks for the topic ;)
I hope that the developers quickly notes issue.

**Comment by cnoon** [comment]
Hi @seart13 and @Flaww,

I still have some more investigation to do here, but the first thing I would do is switch over to using a `LIFO` queue. That will certainly give you much better performance.

```swift
UIImageView.af_sharedImageDownloader = ImageDownloader(downloadPrioritization: .lifo)
```

I'm still looking into other options here.

**Comment by loryhuz** [comment]
@cnoon The problem with lifo is that you can't use collectionView prefetch API then to prefetch images as non-visible cell will have the priority.

A more granular way to handle prioritization for the same image dowloader would be cool

**Comment by cnoon** [comment]
This logic has been redesigned as part of the AFI 4.0.0 release and now cancels the request if there are no other response handlers tracking the same request. The documentation has also been updated to reflect this behavior. The AFI 4.0.0 release will go out shortly.
