### ISSUE TITLE
Headers in alamofireImage request

### ISSUE THREAD

**Issue by edgarplazola** [Alamofire/AlamofireImage#235]
Hi, i have this code, i need to pass bearer token in headers, how i can do this?
      
        Alamofire.request(imageURL).responseImage { response in
            if let image = response.result.value {
                cell.photo.image=image
            }
        }

**Comment by mwazir2** [comment]
`let headers: HTTPHeaders = ["Cookie": "YourKeyExample"]
            Alamofire.request(imageURL!, headers: headers).responseImage { response in
                
                if let image = response.result.value {
                    cell.photo.image = image
                }
            }`
