### ISSUE TITLE
UIImageView extension: crash if URLRequestConvertible throws

### ISSUE THREAD

**Issue by hybridcattt** [Alamofire/AlamofireImage#241]
I am experiencing a reproducible crash while using UIImageView extension, in case if `URLRequestConvertible` passed to `af_setImage` throws.
It crashes in ImageDownloader.swift in `ImageDownloader.ResponseHandler`'s `init` method due to the use of an implicitly unwrapped optional:

<img width="688" alt="screen shot 2017-02-14 at 17 48 34" src="https://cloud.githubusercontent.com/assets/11408899/22939103/f8dee32c-f2dd-11e6-84ea-1ce46ab1f63b.png">

Sample code:
```
extension ImageRequest: Alamofire.URLRequestConvertible {
    public func asURLRequest() throws -> URLRequest {
        guard let url = URL(string: self.urlString) else {
            throw ImageKitError.url
        }
        return URLRequest(url: url)
    }
}
... // UIImageView extension:
let request: ImageRequest = ...
self.af_setImage(withURLRequest: request as URLRequestConvertible,
                         placeholderImage: request.imagePlaceholder?.image,
                         filter: nil,
                         imageTransition: UIImageView.ImageTransition.noTransition,
                         runImageTransitionIfCached: false) { (response: DataResponse<UIImage>) in
... }
```

I am using Xcode 8.2.1, AlamofireImage 3.2.0.

**Comment by cnoon** [comment]
Hi @hybridcattt,

This is certainly a bug in AFI. The image downloader wasn't designed with the idea of having the ability to have `URLRequestConvertible` be able to throw. As a workaround until we get this design flaw properly addressed, I'd suggest you ensure you're requests being sent into the `ImageDownloader` will not throw.

I'll keep this open until we get a PR up to address the underlying issue.

**Comment by hybridcattt** [comment]
Is there a plan to fix this? I can probably help :)

**Comment by cnoon** [comment]
Closing this issue out for PR #392. Please redirect all future comments to that PR. Thanks! 🍻
