### ISSUE TITLE
Cannot remove image from cache

### ISSUE THREAD

**Issue by panleya** [Alamofire/AlamofireImage#250]
Here is my URL:  http://dev.photonapp.net/App/Images/User/2/

Here is how I'm loading the image into a UIImageView:

```
if let url = URL(string: "http://dev.photonapp.net/App/Images/User/2/") {
     avatarImage.af_setImage(withURL: url, placeholderImage: UIImage(named: "Avatar"))
}
```

Later, after the user picks an image from their photo library, I upload the new image to the server (checked, yes this works), manually remove the image from the cache, and re-download:

```
public func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
    let img = info[UIImagePickerControllerEditedImage] as! UIImage
        
    //clear from cache
    let url = URL(string: "http://dev.photonapp.net/App/Images/User/2/")!
    let urlRequest = URLRequest(url: url)
    let imageDownloader = UIImageView.af_sharedImageDownloader
    _ = imageDownloader.imageCache?.removeImage(for: urlRequest, withIdentifier: nil)
    imageDownloader.sessionManager.session.configuration.urlCache?.removeCachedResponse(for: urlRequest)
        
    //upload to the interwebs
    let data = UIImageJPEGRepresentation(img, 0.8)
    let attachmentBody = data?.base64EncodedString(options: NSData.Base64EncodingOptions()) ?? ""
        
    //upload the new avatar to the server
    PWSecurityService.shared.setUserData(attachmentBody, type: .avatar) { (status, message, error) in
        self.avatarImage.af_setImage(withURL: url)
    }
        
    //hide the popup
    dismiss(animated: true, completion: nil)
}
```

This DOES NOT work.  The old image stays in cache, and even after reloading the app it still shows the original image, despite the URL showing the upload working.  WTF am I doing wrong??  Why does something so obvious and simple (removing an image from cache based on a URL) take so many lines of code and still not work??

**Comment by htarwara6245** [comment]
+1

**Comment by douglas-srs** [comment]
Fastest way to solve this is by giving your new uploaded images a random name, it caches the image using the url as key, had the same problem and solved with this workaround.

**Comment by htarwara6245** [comment]
@douglas-srs
Yeah it was, but sometime we need to add only static image url inside. The main problem of this issue was "How to clean disk cache for specific image."

**Comment by panleya** [comment]
I WANT the image to stay cached, until the user uploads a new one.  Changing the name like you suggest effectively turns off the cache.  Again, adding AND removing items from cache is 101 stuff for having a cache.  Can someone from the development group address this please??

**Comment by htarwara6245** [comment]
Try use that : https://github.com/onevcat/Kingfisher. Since this library is open-source, they just share what they can. Some of them might busy. So, try use the above library that I provided you. At that library you can control your own cache (memory cache and disk cache), image downloader. So, create your own image downloader and clean the cache when you are ready to remove.

**Comment by douglas-srs** [comment]
@htarwara6245 Oh, I get it now but for me this isn't the case because my App has also a web app which the user can upload his picture as well and if I don't use a dynamic image name cache wouldn't work as expected because I can't clean the users phone's cache from a web browser :P

**Comment by panleya** [comment]
@htarwara6245 I have no interest in ripping out all my code and switching libraries simply because an obvious issue isn't being addressed by the developers.  I'd rather they just address it.

**Comment by jshier** [comment]
@panleya As you can see in our [tests](https://github.com/Alamofire/AlamofireImage/blob/master/Tests/ImageCacheTests.swift#L140), cache removal works just fine. In fact, I added a new test specifically for the `UIImageView` extension to make sure it still works there as well, in PR #254. I suggest you investigate and make sure your identifiers are the same. You may also want to stop ignoring the return value of `removeImage`, as that should let you know whether the image was removed at all.

**Comment by panleya** [comment]
There was an extra "/" in my URL.  Once I removed it the code worked better.  I don't know why it would break things.  The remove returned true, and the code did in fact re-download the image, yet the downloader returned the old image rather than the one updated on the server.  Somehow, via magic it appears, the extra "/" in the URL once removed made that all work.  Hocky at best.

**Comment by jshier** [comment]
It's not magic. If using the URL as the key, you need to match it exactly for the cache to think it's the same key. I suggest you come up with a way of storing relevant `URL`s or `URLRequest`s for later access if you need to use them for cache access.
