### ISSUE TITLE
SPM Error: the package has an unsupported layout

### ISSUE THREAD

**Issue by scottdelly** [Alamofire/AlamofireImage#251]
Apple Swift version 3.1 (swiftlang-802.0.51 clang-802.0.41)
Target: x86_64-apple-macosx10.9

The issue:

`error: the package has an unsupported layout, unexpected source file(s) found: .build/checkouts/AlamofireImage-6503021523934871910/Tests/*.swift`

There are 2 options as far as I can tell:

- Alamofire fixes this by adding:
`exclude: ["Tests"]` to their Package.swift
see here : https://github.com/Alamofire/Alamofire/blob/master/Package.swift

- SwiftyJSON fixes this by moving the source files 1 level deeper into:
`Tests/SwiftJSONTests`
as seen here: https://github.com/SwiftyJSON/SwiftyJSON/pull/707/files

Not sure about pros and cons, but would really appreciate being able to use this module in a server side project :)

Thanks!

**Comment by jshier** [comment]
Thanks for the report! I just merged a PR that fixes this.
