### ISSUE TITLE
[wish] integration with ASNetworkImageNode from AsyncDisplayKit

### ISSUE THREAD

**Issue by dodikk** [Alamofire/AlamofireImage#255]
AS a developer (library user)
I'D LIKE  TO have `AlamofireImage` conforming `ASImageCacheProtocol` and `ASImageDownloaderProtocol` from `AsyncDisplayKit`

SO THAT I avoid having multiple networking wrappers in my app
AND I add app specific authentication headers to network image requests just like I do it for the rest of my application.

**Comment by dodikk** [comment]
So I've sub-classed the `ASImageCacheProtocol` and `ASImageDownloaderProtocol`.
Seems to work for me but there is likely a lot to improve.

https://gist.github.com/dodikk/2e1a2811eee00af5ea02004d640292bf

**Comment by dodikk** [comment]
P.S. Leaving the "integration" part to `AlamofireImage` maintainers.

**Comment by jshier** [comment]
We won't be directly integrating support for any third party protocols or libraries. AlamofireImage is designed to be extensible enough for you to do that yourself. Feel free to open issues or PR (preferably) if you need increased flexibility somewhere. Also, creating your own open source integration would be a good way to contribute back to the community.
