### ISSUE TITLE
AlamofireImage displays cached image even though the url query parameter changed

### ISSUE THREAD

**Issue by funkenstrahlen** [Alamofire/AlamofireImage#256]
I use **AlamofireImage** in my iOS app to fetch images from the backend. (iOS 10.3.2, AlamofireImage 3.2.0)

`coverartImageView.af_setImage(withURL: coverartUrl)`

I do not use `AutoPurgingImageCache`.

The url to an image looks like this:

`https://someUrl/1475.jpg?f5a189e2303a28751a7da38be543be7f`

If the image is changed on the backend the url changes to this for example:

`https://someUrl/1475.jpg?dfgkjhdfgkj235kjgliuh34tkleybglk`

**What happens:**
AlamofireImage displays the old image when called with the new url.

**What I expect:** The url query parameter did change. I expect AlamofireImage to load the new image.

Do url query parameters not count as a new url, so it does use the old cache? I could not find any documentation about this.

**Comment by jshier** [comment]
If you're not using the `AutoPurgingImageCache`, AlamofireImage isn't doing any caching for you. The only other cache that would be active is the `URLCache` for the underlying `URLSession`. I'm not sure whether that will always invalidate based on parameters or not. You should check the contents of that cache to make sure.
