### ISSUE TITLE
Can not support disk cache

### ISSUE THREAD

**Issue by alafata100** [Alamofire/AlamofireImage#258]
Is that a plan to add the disk cache support?

**Comment by mwaqasbhati** [comment]
Disk Cache is support is provided in this library. You can check their library documentation there is clearly written::

The ImageDownloader uses a combination of an URLCache and AutoPurgingImageCache to create a very robust, high performance image caching system.

The URLCache is used to cache all the original image content downloaded from the server. By default, it is initialized with a memory capacity of 20 MB and a disk capacity of 150 MB. This allows up to 150 MB of original image data to be stored on disk at any given time.

**Comment by cnoon** [comment]
We will not be adding on-disk cache support anytime soon. Please see #5 for more details.

**Comment by VRCorp** [comment]
Hi @cnoon - can you help me to understand => your documentation [link](https://github.com/Alamofire/AlamofireImage#url-requests) says that on-disk cache is supported but the issue [#5](https://github.com/Alamofire/AlamofireImage/issues/5) says it won't be supported anytime soon.

So what is correct? Is the on-disk cache supported ?
(If not supported, can you please update the documentation to avoid people are mislead by this)

Thanks for all your precious work!

**Comment by oalvarez** [comment]
What happened with this? Is it implemented, or is it going to be implemented any time soon?
Are the docs still wrong?

**Comment by jshier** [comment]
On disk caching is supported through `URLCache`. The caches that AFI provides for the fully processed images only support in-memory caching.

We'd like to add specific disk caching but won't be doing so any time soon.
