### ISSUE TITLE
`EXC_BAD_ACCESS` crash reported on Crashlytics for iPad devices

### ISSUE THREAD

**Issue by jpodcedensek** [Alamofire/AlamofireImage#263]
We are using AlamofireImage in our app and we are getting some crashes reported by Crashlytics as `EXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x0000000000000000`. At first it looks like an issue is due to low memory, but I still wanted to notify you about this.

The relevant app version was built using XCode 8.3.2. We are targetting iOS 8+ devices.

The crash occured about ten times, always on an iPad.  Crashlytics log is attached.
[crashlytics_log.txt](https://github.com/Alamofire/AlamofireImage/files/1020124/crashlytics_log.txt)

For some reason I can`t get statistics for all crashes on Crashlytics dashboard so I am attaching screenshots from Fabric app (note: these are for two separate apps):
![img_0504_](https://cloud.githubusercontent.com/assets/17743356/26327037/05af2f88-3f3e-11e7-9c50-719905309f53.png)

![img_0503](https://cloud.githubusercontent.com/assets/17743356/26327038/05b013e4-3f3e-11e7-8f95-5ae8f1ce4d81.PNG)

Unfortunately we were not able to reproduce the issue. Hopefully you can get the required info from my submission, if not, I will try my best to provide more data.

**Comment by djk12587** [comment]
How large are the images you are trying to load? I've seen this crash before where we had a tableview rapidly loading large images roughly 2-3mb. This ate up a lot of memory and eventually crashed the app. Turns out our backend was sending the full resolution when they should have been sending a small thumbnail. Switched it to a thumbnail and no more memory issues and crashes.

**Comment by cnoon** [comment]
You have to be careful when loading images into memory that you don't run yourself out-of-memory! There's nothing AFI can do to prevent you from doing this other than automatically clear the cache when you're running out which we already do. Please see #115 for more info.

Best of luck! 🍻
