### ISSUE TITLE
How to run Example project

### ISSUE THREAD

**Issue by asadali737** [Alamofire/AlamofireImage#264]
How could I run example projects?
There's no pod file included in current commit, so I can install the pod if needed. 
No luck even if I run the `AlamofireImage.xcworkspace` file.

**Comment by cnoon** [comment]
Hi @asadali737,

You need to update the submodule which can be done with `git submodule update --init`. Then you just need to open up the `AlamofireImage.xcworkspace`, set the build target to the `iOS Example`, and build and run.

Best of luck! 🍻
