### ISSUE TITLE
Does not compile with Swift 4

### ISSUE THREAD

**Issue by ldiqual** [Alamofire/AlamofireImage#265]
Compilation on Swift 4 fails in ImageCache.swift on the following line: https://github.com/Alamofire/AlamofireImage/blob/master/Source/ImageCache.swift#L200

```swift
var sortedImages = self.cachedImages.map{$1}
// Source/ImageCache.swift:200:57: Closure tuple parameter '(key: String, value: AutoPurgingImageCache.CachedImage)' does not support destructuring with implicit parameters
```

**Comment by cnoon** [comment]
We will be adding Swift 4 support shortly. It also looks like you've already opened #266 which adds support. I'm going to close this issue out for now. Please direct all further comments to #266.
