### ISSUE TITLE
Store images on disk

### ISSUE THREAD

**Issue by kimdv** [Alamofire/AlamofireImage#27]
Hey! 

I have an idea for a feature. 

Some apps store images in the disk and i could work following

1: The app check if the image is stored on the disk
2: If the image is stored on the disk, i should load it
 - If it's not stored i download the image. 

It would be a sweet ass feature for AlamofireImage :o)

Cheers
// Kim

**Comment by cnoon** [comment]
Already implemented automatically by `NSURLCache`! 🎉 🎉 🎉 

Also see #5 for more info.
