### ISSUE TITLE
Purging images from ImageCache based on ETag

### ISSUE THREAD

**Issue by bhsgsh10** [Alamofire/AlamofireImage#270]
I went through the discussions here: https://github.com/Alamofire/AlamofireImage/issues/5 and here: https://stackoverflow.com/questions/21659764/nsurlcache-and-etags
The issue I'm facing is as follows:
I'm setting images to the UIImageViews in my application using af_setImage(withURL: url). The image gets cached by Alamofire as expected. But the thing is that the image might change in the backend. The backend is sending me ETag but not cache control in the response headers.
According to the 2nd link mentioned above, NSURL has automatic handling for ETag. This approach did not work for me.
In the first discussion @cnoon has mentioned that "UIImageView and the ImageDownloader only searches in the ImageCache for the cached image. It doesn't look into the NSURLCache", which is probably why the first approach failed. 
As of now, the current image does not reflect in the app as the older image is found in the cache. How can we purge the ImageCache based on changes to ETag?

**Comment by jshier** [comment]
You'd essentially have to write your own `ImageCache` conforming type that can look into the `URLCache` to invalidate images stored in an in-memory cache. Basically the functionality `AutoPurgingImageCache` combined with functionality to inspect the `URLCache`. If you come up with something we'd be happy to hear about it!
