### ISSUE TITLE
AlamoFireImage cache filtered and original image

### ISSUE THREAD

**Issue by ceichin** [Alamofire/AlamofireImage#275]
When applying a filter, the filtered image gets cached:
```
let filter = AspectScaledToFillSizeWithRoundedCornersFilter(
   size: kSize,
   radius: kRadius
)

myImageView.af_setImage(
   withURL: imageUrl,
   placeholderImage: placeholderImage,
   filter: filter
)
```

But afterwards, when I do a request for the NOT filtered image (the original image), it is not cached:
```
myImageView.af_setImage(
   withURL: imageUrl,
   placeholderImage: placeholderImage
)
```

In the first call the original image is downloaded, but only the filtered image is cached. I would like that the filtered image AND the original image get cached at once in the first call. Is there a possibility to do this elegantly? Thanks!

**Comment by jshier** [comment]
There doesn't currently exist a way to do this elegantly. You should have the original images cached in the `URLCache` used by the `ImageDownloader`, but you'll want to make sure it's setup with the right capacity. Also, if your server doesn't return appropriate cache headers then it may not work anyway. We'll be reexamining caching in the next release.
