### ISSUE TITLE
Class var 'imageScale' is not public

### ISSUE THREAD

**Issue by Ddjay** [Alamofire/AlamofireImage#279]
I have some errors with AlamofireImage and Xcode Version 9.0 beta 3 (9M174d):

on these classes : 

- `public class func imageResponseSerializer(`
  > Class var 'imageScale' is private and cannot be referenced from a default argument value
 
- `public func responseImage(`
  > Class var 'imageScale' is private and cannot be referenced from a default argument value
 
- `public func streamImage(`
  > Class var 'imageScale' is private and cannot be referenced from a default argument value
 
- and finally in ImageDownloader.swift:278:50
   > Instance method 'append' expects a single parameter of type '(receiptID: String, filter: ImageFilter?, completion: ImageDownloader.CompletionHandler?)' (aka '(receiptID: String, filter: Optional<ImageFilter>, completion: Optional<(DataResponse<UIImage>) -> ()>)')

<img width="260" alt="capture d ecran 2017-08-10 a 15 38 30" src="https://user-images.githubusercontent.com/5408562/29172992-0f149080-7de2-11e7-85fe-b9c55398b2e7.png">

Is this a problem with Xcode? I am a beginner in swift development.
What can I do to fix this issue?

Thanks a lot for your help.

Did

**Comment by marnap89** [comment]
Same from me :(

**Comment by htinlinn** [comment]
@Ddjay I was running into a similar issue and it seems like the fix for this is already in the `master` branch. There just hasn't been a new release with it yet. 

Until there is a new release, you can get around the issue by getting the source from [this commit](https://github.com/Alamofire/AlamofireImage/commit/a1e44d9aae082d141d062c2b601f8057538c668a).

**Comment by tvtruong3964** [comment]
i have same issues, try to pod 'AlamofireImage', '~> 3.3' and pod 'Alamofire', '~> 4.5' (note version compatibility Alamofire and AlamofireImage). If you have error when install then try to "pod install --repo-update"

i hope help you.
