### ISSUE TITLE
Please consider new release

### ISSUE THREAD

**Issue by sanmai** [Alamofire/AlamofireImage#285]
* [x] I've read, understood, and done my best to follow the [CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

Installed latest release version from CocoaPods. Specifically 3.2.0.

## What did you expect to happen?

I expected scaling operations work when loading and scaling images within UIImageView if the target view is set to size with content.

## What happened instead?

Hitting bug #226. Getting "fatal error: unexpectedly found nil while unwrapping an Optional value" at this line:

    let scaledImage = UIGraphicsGetImageFromCurrentImageContext()!

## Possible solution

Please consider crafting a new release with #226 fixed. As it is now since PR #244. Thanks.

**Comment by cnoon** [comment]
Coming soon @sanmai in https://github.com/Alamofire/AlamofireImage/pull/287. 👍🏻
