### ISSUE TITLE
Add "image/jpg" to the list of acceptableContentTypes

### ISSUE THREAD

**Issue by Codeglee** [Alamofire/AlamofireImage#29]
I'm not sure why it isn't already in the list but please add "image/jpg" here:

`private class func validateResponse(response: NSHTTPURLResponse?) -> Bool {

        let acceptableContentTypes: Set<String> = [
            "image/tiff",
            "image/jpeg",
            "image/gif",
            "image/png",
            "image/ico",
            "image/x-icon",
            "image/bmp",
            "image/x-bmp",
            "image/x-xbitmap",
            "image/x-win-bitmap"
        ]`

It's in Request+AlamofireImage.swift.

"image/jpg" is a valid content type and behaves identically to "image/jpeg".

Thanks.

**Comment by cnoon** [comment]
Hi @Codeglee, `image/jpg` is not a valid MIME type, but it is used as a content-type all over the place incorrectly. We need to make some changes to AFI to allow users to add additional acceptable content types. See #28 for more information.

I'll most likely be making some changes here soon (next couple days) to make this much easier to customize.

**Comment by Codeglee** [comment]
Hey @cnoon,

You're right, I mistook ubiquity for standards compliance.

I'm sure others are in the same place we are, having to consume third party APIs that aren't compliant.

Any extensibility points you add to resolve this scenario would be fine. For the moment I've just branched the code but will keep an eye out for updates.

**Comment by cnoon** [comment]
Pull request #33 adds the ability to specify additional acceptable image content types for a `Request`. I'm going to close this issue out. Please redirect all further comments to #33.
