### ISSUE TITLE
Carthage failed building

### ISSUE THREAD

**Issue by sylvaindieterle** [Alamofire/AlamofireImage#292]
Hello,
With the last version of ios 11 and xcode 9.0 lately. Building failed on this update with Carthage.

``
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/../Carthage/Checkouts/AlamofireImage/AlamofireImage.xcworkspace -scheme AlamofireImage\ iOS -configuration Release -derivedDataPath /Users/../Library/Caches/org.carthage.CarthageKit/DerivedData/9.0_9A235/AlamofireImage/3.3.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO BITCODE_GENERATION_MODE=bitcode CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES build (launched in /Users/../Carthage/Checkouts/AlamofireImage)
``

**Comment by jshier** [comment]
The Carthage checkout has been updated. Everything should be building correctly now.

**Comment by LeeTwelve** [comment]
I have a same issue:
``
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Volumes/MASS/.../ios/Carthage/Checkouts/AlamofireImage/AlamofireImage.xcworkspace -scheme AlamofireImage\ iOS -configuration Release -derivedDataPath /Users/.../Library/Caches/org.carthage.CarthageKit/DerivedData/11.2.1_11B500/AlamofireImage/4.0.2 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/4b/sn80n6bs3v91z5kcwkltdc8m0000gn/T/AlamofireImage SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Volumes/MASS/.../ios/Carthage/Checkouts/AlamofireImage)
``
