### ISSUE TITLE
af_setImage race condition when runImageTransitionIfCached=true

### ISSUE THREAD

**Issue by RonaldAndersonAol** [Alamofire/AlamofireImage#293]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

Used af_setImage extension function on UIImageView, with runImageTransitionIfCached=true. When the image is found in the cache, the transition is run on a delayed (0.001 sec) GCD block. This is fine, except for when the image request is canceled with a call to af_cancelImageRequest. The subsequent new image request may get overridden with the delayed block, if the next request also fetches the image from the cache, but has runImageTransitionIfCached=false. Then the "cancelled" cached image will overwrite the new cached image.

Proposed solution:

UIImageView+AlamofireImage.swift : line 287

OLD:

if runImageTransitionIfCached {
     let tinyDelay = DispatchTime.now() + Double(Int64(0.001 * Float(NSEC_PER_SEC))) / Double(NSEC_PER_SEC)
     // Need to let the runloop cycle for the placeholder image to take affect
     DispatchQueue.main.asyncAfter(deadline: tinyDelay) { [weak self] in
          self.run(imageTransition, with: image)
          completion?(response)
     }
}

NEW:

if runImageTransitionIfCached {
     if let placeholderImage = placeholderImage { self.image = placeholderImage }

     self.run(imageTransition, with: image)
     completion?(response)
}

## What did you expect to happen?

The second image request should not get overwritten with the cancelled image.

## What happened instead?

The first cancelled image overwrote the subsequent image request image.

## Alamofire Environment

**Alamofire version: 4.5.1**
**Xcode version: 9.0 (9A235)**
**Swift version: 4.0**
**Platform(s) running AlamofireImage: tvOS**
**macOS version running Xcode: 10.12.6**

## Demo Project

None

**Comment by cnoon** [comment]
Closing this issue out for PR #294. Please direct all further comments to that PR. Thanks!
