### ISSUE TITLE
setImage sometimes loads an image and fails showing during animation

### ISSUE THREAD

**Issue by bartando** [Alamofire/AlamofireImage#295]
* [ ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

I’ve set my af_image in RxSwift’s onNext like this

`self.currentMovieBackground.af_setImage(
                    withURL: self.imageManager.getPosterImageUrl(imageRes: .big, imageUrl: movie?.poster),
                    placeholderImage: nil,
                    filter: nil,
                    imageTransition: .crossDissolve(0.8)
                )`

## What did you expect to happen?

The image should be replaced with wanted image as soon as its downloaded. Best solution would be with the crossDissolve animation between old and new image. (Which happens most of the time)

## What happened instead?

Sometimes the image i want to have downloaded and then shown, happens to be replaced by very first loaded image in the image view. 

Here's video:
https://www.youtube.com/watch?v=FSyDiGQ-29I

## Alamofire Environment

**Alamofire version:** 3.3
**Xcode version:** 9.0 GM
**Swift version:** 3.2
**Platform(s) running AlamofireImage:** iOS 11
**macOS version running Xcode:** 10.12.6

## Demo Project

I would love to share my project with you, if there is possibility how to show you or send you my project, that would be awesome. I just don't want to make it public trough here...

**Comment by bartando** [comment]
I'm sorry, I've figured that this was my own issue. Not sure how to close this :/

**Comment by falsecrypt** [comment]
@bartando What was the problem?

**Comment by bartando** [comment]
I was setting the image back to the first one. My mistake :)

**Comment by jshier** [comment]
Thanks for letting us know how it turned out!
