### ISSUE TITLE
ImageView on TableViewCell changes size on tap or reload of cell

### ISSUE THREAD

**Issue by dwightwatson** [Alamofire/AlamofireImage#30]
I'm trying to set the image view on a `UITableViewCell` subclass using the helper with a placeholder. 

It works fine, and when the image is loaded the placeholder is replaced with the correct image. However, upon tapping on the cell (or forcing the cell to reload by scrolling it out of view and then bringing it back in) the image view snaps to a smaller version of the image.

    self.imageView?.af_setImageWithURL(categoryImageUrl, placeholderImage: UIImage(named: "DefaultCategory"))

For example, here is how the cell appears after the initial load:

![image](https://cloud.githubusercontent.com/assets/1100408/10382139/97f468d0-6e6c-11e5-9f74-377047f701e3.png)

Then, once the cell has been tapped/reloaded it appears as this:

![image](https://cloud.githubusercontent.com/assets/1100408/10382143/a31d981c-6e6c-11e5-9d97-a630171fc61b.png)

How can I have the image set at the right size initially, or prevent a resize from occurring upon reload?

**Comment by cnoon** [comment]
I'd say this is not an issue related to AlamofireImage but rather to your `UITableViewCell` layout. There shouldn't be anything in AlamofireImage controlling the size of the image view. Nor are you using image filters. You'll just need to keep digging.

If you end up finding an actual issue in AFI, please add some additional info about the problem and I'll be happy to re-open the issue.
