### ISSUE TITLE
Response Content-Type was missing and acceptable content types

### ISSUE THREAD

**Issue by Isuru-Nanayakkara** [Alamofire/AlamofireImage#301]
## What did you do?

I'm trying to fetch an image from a website. First I tested it in Chrome's network inspector and got the request as a cURL request. Here it is.

```
curl 'https://www.internetvas.slt.lk/SLTVasPortal-war/javax.faces.resource/dynamiccontent.properties.nable?ln=primefaces&v=6.0&pfdrid=45b3765f-0edd-4ba6-9c11-3d9a5983c0a2&pfdrt=sc&pfdrid_c=false&uid=1462a152-d2c6-4a87-af99-107c4e432b1b' \
-X GET \
-H 'Referer: https://www.internetvas.slt.lk/SLTVasPortal-war/application/index.nable' \
-H 'Host: www.internetvas.slt.lk' \
-H 'Accept: image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5' \
-H 'Connection: keep-alive' \
-H 'Accept-Language: en-us' \
-H 'Accept-Encoding: br, gzip, deflate' \
-H 'User-Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7' \
-H 'Cookie: JSESSIONID=1DCB8AF2636491542219E00AE5EAC9B0; BNI_persistence=000000000000000000000000d3011fac0000901f; JSESSIONID=DFAFA4B636FD3ED38190168D01586F44; _ga=GA1.2.1939120074.1468438058'
```

Then I tried to replicate it with AlamofireImage. Here is my code.

```swift
let urlString = baseURLString + "javax.faces.resource/dynamiccontent.properties.nable?ln=primefaces&v=6.0&pfdrid=45b3765f-0edd-4ba6-9c11-3d9a5983c0a2&pfdrt=sc&pfdrid_c=false&uid=1462a152-d2c6-4a87-af99-107c4e432b1b"

DataRequest.addAcceptableImageContentTypes(["image/*", "image/png", "image/svg+xml", "*/*"])

let headers: HTTPHeaders = [
    "Accept":"image/png,image/svg+xml,image/*;q=0.8,*/*;q=0.5",
    "Accept-Encoding":"br, gzip, deflate",
    "Connection":"keep-alive",
    "Referer":"https://www.internetvas.slt.lk/SLTVasPortal-war/application/index.nable",
    "Cookie":"JSESSIONID=1DCB8AF2636491542219E00AE5EAC9B0; BNI_persistence=000000000000000000000000d3011fac0000901f; JSESSIONID=DFAFA4B636FD3ED38190168D01586F44; _ga=GA1.2.1939120074.1468438058",
    "Host":"www.internetvas.slt.lk",
    "User-Agent":"Mozilla/5.0 (Macintosh; Intel Mac OS X 10_13_2) AppleWebKit/604.4.7 (KHTML, like Gecko) Version/11.0.2 Safari/604.4.7",
    "Accept-Language":"en-us",
]

Alamofire.request(urlString, method: .get, headers: headers).responseImage { response in
    print(response)
    switch response.result {
    case .success(let image):
        print(image)
    case .failure(let error):
        print(error.localizedDescription)
    }
}
```

## What did you expect to happen?

The image to be fetched.

## What happened instead?

The request keeps failing with the following error even after I added the line `DataRequest.addAcceptableImageContentTypes`.

> FAILURE: responseValidationFailed(Alamofire.AFError.ResponseValidationFailureReason.missingContentType(["image/x-icon", "image/ico", "image/x-bmp", "image/x-xbitmap", "image/tiff", "image/*", "image/svg+xml", "image/jpeg", "image/bmp", "image/png", "*/*", "image/x-ms-bmp", "image/gif", "image/x-win-bitmap"]))
Response Content-Type was missing and acceptable content types (image/x-icon,image/ico,image/x-bmp,image/x-xbitmap,image/tiff,image/*,image/svg+xml,image/jpeg,image/bmp,image/png,*/*,image/x-ms-bmp,image/gif,image/x-win-bitmap) do not match "*/*".

This is the returned http response's headers.

```
HTTP/1.1 200 OK
X-Frame-Options: SAMEORIGIN
X-Content-Type-Options: nosniff
X-Powered-By: JSF/2.0
Transfer-Encoding: chunked
Date: Thu, 28 Dec 2017 14:23:48 GMT
Server: 
Set-Cookie: BNI_persistence=000000000000000000000000d3011fac0000901f; path=/; HttpOnly
```

I suspect the `X-Content-Type-Options: nosniff` might have something to do with this but I'm not sure.

## Alamofire Environment

**Alamofire version:** 4.6.0
**AlamofireImage version:** 3.3.0
**Xcode version:** 9.1
**Swift version:** 4
**Platform(s) running AlamofireImage:** iOS
**macOS version running Xcode:** 10.13.2

## Demo Project

[Demo project](https://www.dropbox.com/s/ugq8b27iva33fej/ImageFetchDemo.zip?dl=0)

**Comment by jshier** [comment]
You can customize the acceptable content types, as explained in our [docs](https://github.com/Alamofire/AlamofireImage#usage), to workaround improper server responses.
