### ISSUE TITLE
CocoaDocs Documentation is broken

### ISSUE THREAD

**Issue by franiis** [Alamofire/AlamofireImage#305]
* [*] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

I tried to access documentation http://cocoadocs.org/docsets/AlamofireImage/3.3.0/

## What did you expect to happen?

I expected to see documentation.

## What happened instead?

I found broken documentation with information about parsing error.

## Alamofire Environment

**Alamofire version:** 3.3.0
**Xcode version:** not relevant
**Swift version:** not relevant
**Platform(s) running AlamofireImage:** MacOS, Google Chrome
**macOS version running Xcode:** not relevant

## Demo Project

(link from README.md to documentation):
http://cocoadocs.org/docsets/AlamofireImage/3.3.0/

**Comment by loudmouth** [comment]
CocoaDocs is no longer supported/maintained so this is expected behavior and this ticket should be closed. See the blog post by the original maintainer:

http://blog.cocoapods.org/CocoaDocs-Documentation-Sunsetting/

**Comment by franiis** [comment]
Yeah, you're right. I didn't know that. 
I think that this fact should be pointed next to link on README.md.

Thank you.

**Comment by loudmouth** [comment]
Oh yeah, didn't see the link right on the README, definitely seems like it should be pruned/replaced...
