### ISSUE TITLE
Feature request: image/vnd.microsoft.icon support

### ISSUE THREAD

**Issue by SMillerDev** [Alamofire/AlamofireImage#307]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

Pulled favicon images from various sources.

## What did you expect to happen?

All of them loaded correctly

## What happened instead?

Only icons that didn't follow the IANA standard loaded

## Desctription

As [this stackoverflow post](https://stackoverflow.com/questions/13827325/correct-mime-type-for-favicon-ico) indicates, there's not really a good standard for favicon mime types. AlamofireImage however only supports 1 of the 2 options that's regularly used, making a lot of favicons fail to load.

The main purpose of this issue is to see if there's any use proposing a pull request that adds support for the `image/vnd.microsoft.icon` type.

**Comment by jshier** [comment]
Given that the "standard" isn't actually a standard (Microsoft didn't register it), and it's easy to add such a type to the accepted types, as outlined in our [docs](https://github.com/Alamofire/AlamofireImage#usage), we won't be adding support for this type.
