### ISSUE TITLE
App crash on large image

### ISSUE THREAD

**Issue by akashpopat** [Alamofire/AlamofireImage#308]
## What did you do?

Run this in a UICollectionViewCell

`if let url = URL(string: group.mainImage) {
            imageView.af_setImage(withURL: url)
        }`

## What did you expect to happen?

Load image in the cell.

## What happened instead?

All images load properly and run but if I use an image of size 20MB, the app memory usages increases to 600MB from 50 MB. The image url = http://lc.seenit.in/batch_images/Pizigani_1367_Chart_10MB.jpg

**Comment by jshier** [comment]
Large images require a lot of memory to display, so I suggest you ether download it and resize it for display on device, or request it in a size that can be more easily displayed without your app being killed by the system watchdog.
