### ISSUE TITLE
ImageDownloader setting Session's `startRequestsImmediately` property to false?

### ISSUE THREAD

**Issue by mattinasi** [Alamofire/AlamofireImage#312]
* [x ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

Initialized an ImageDownloder with my own SessionManager (for authorizing image access)

## What did you expect to happen?

I expected the SessionManager to be used for Image Downloads, but not for the `startRequestsImmediately` property of the SessionManager to be changed to `false`

## What happened instead?
`startRequestsImmediately` property on my SessionManager is set to `false`, which changes the behavior of the SessionManager for all other usage

I am wondering if it is required for the ImageDownloader to set the `startRequestsImmediately` property to false, and if I reset it to `true` after initializing the ImageDownloader can I expect any issues?

## Alamofire Environment

**Alamofire version:**
3.3.1
**Xcode version:**
9.2 / 9.3
**Swift version:**
4.0 / 4.1
**Platform(s) running AlamofireImage:**
iOS 11.2
**macOS version running Xcode:**
10.13.4

**Comment by mattinasi** [comment]
I am presuming that the ImageDownloder wants to control when requests are started, so it can manage a limited number of simultaneous requests... and that is maybe why it is setting this SessionManager property to `false`. 

I think it is a worthwhile side-effect to document, if indeed it is required for the ImageDownloder.

**Comment by jshier** [comment]
You're correct. Unfortunately this isn't something we can really change at the moment, but a documentation PR is always appreciated.
