### ISSUE TITLE
Does setImage cache?

### ISSUE THREAD

**Issue by martheli** [Alamofire/AlamofireImage#315]
I read through the documentation and I see af_setImage sets the image if it is cached but if it is not cached does it set the image to the cache automatically so then the next time I call setIamge it will take it from cache? Does that caching and checking process happen automatically within the setImage function?

**Comment by jshier** [comment]
Caching is automatic, but is only in memory, there is no persistent cache between app relaunches, unless the image was cached in the `URLCache`.
