### ISSUE TITLE
af_setImage(withURL: url) memory leak

### ISSUE THREAD

**Issue by RobertHaworth** [Alamofire/AlamofireImage#318]
* [X ] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

I attempted to load an image from a URL using the following UIImageView extension function:

af_setImage(withURL: url)

## What did you expect to happen?

I expected the image to be loaded without leaking memory

## What happened instead?
I have confirmed the image loads as expected, but there is a memory leak that occurs.

## Alamofire Environment

**Alamofire version:** 4.7.2
**Xcode version:** 9.4.1
**Swift version:** 4.1
**Platform(s) running AlamofireImage:** Cocoapod -> 3.3.1
**macOS version running Xcode:** 10.13.6

## Demo Project

Attached is a fully functioning example of the project. and a screenshot of the Memory Graph showing the leak and backtrace.
[AlamofireLeak.zip](https://github.com/Alamofire/AlamofireImage/files/2186064/AlamofireLeak.zip)

![screen shot 2018-07-11 at 2 43 59 pm](https://user-images.githubusercontent.com/1219463/42596686-291942d6-851c-11e8-8334-089a6a599741.png)

**Comment by pitchmak** [comment]
I encounter this issue as well when I attempted to load an image from a URL using the following UIImageView extension function: af_setImage(withURL: url)

It happened when I tried to load 4 images at the same time but not with 2 images.

my env is
**Alamofire version:** 4.7.3
**Xcode version:** 10.0 beta 2
**Swift version:** 4
**Platform(s) running AlamofireImage:** Carthage -> 0.29.0
**macOS version running Xcode:** 10.13.4

**Comment by RSickenberg** [comment]
Same 👍

**Comment by jshier** [comment]
Not currently detecting any leaks. Perhaps this is something only seen on device?

**Comment by cnoon** [comment]
The original issue was filed running on a device, so I'd assume that's the kicker. We should test to see if we can track down the core issue. Not sure that it's actually our code that's leaking, but we should try to see if we can reproduce it.

**Comment by cnoon** [comment]
I just profiled `master` against all the logic in AFI 4.0.0 and don't see any issues. I'm going to close this issue out for now as resolved with AF5 and AFI4. If anyone sees any issues on AFI4, please feel free to comment here or open a new issue.
