### ISSUE TITLE
Images cache in AutoPurgingImageCache only available when app is currently running?

### ISSUE THREAD

**Issue by Shempaiii** [Alamofire/AlamofireImage#322]
* [*] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

- Cache URLRequest using AutoPurgingImageCache works fine when app is currently running

## What did you expect to happen?

- I can get those cache images again

## What happened instead?

- Those cache images can't fetch again using URLRequest

## Alamofire Environment

**Alamofire version:**

**Xcode version:**
9.4.1

**Swift version:**
4.0

**Platform(s) running AlamofireImage:**

**macOS version running Xcode:**
10.13.16

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by shemchavez** [comment]
Thanks @jshier 🙂
