### ISSUE TITLE
af_setImage with download location to document directory.

### ISSUE THREAD

**Issue by ShahVivek** [Alamofire/AlamofireImage#325]
I want to download media files in document directory and display it to the imageView of a tableViewCell once download gets completed. The same functionality which provided by af_setImage, but af_setImage store image in cache, and my requirement is to store image in document directory.
`af_setImage(withURL: url, placeholderImage: placeholderImage)` 

Rightnow I am using Alamofire.download method, but when I am scrolling the tableview, image attaches to the different cells.
`Alamofire.download(url: url, method: .get, parameters: nil, encoding: JSONEncoding.default, headers: nil, to: DownloadRequest.suggestedDownloadDestination(for: .documentDirectory))`

Anyone can please help me in this scenario?

## Alamofire Environment

**Alamofire version: 4.7.3**
**Xcode version: 9.4.1**
**Swift version: 4**
**Platform(s) running AlamofireImage: 3.3.1**
**macOS version running Xcode: 10.13.6**

**Comment by jshier** [comment]
Most likely you need to cancel or otherwise disassociate your file downloads from individual cells, perhaps by implementing `prepareForReuse`. Download disk and use `af_setImage` to load the image from the file URL may work to load the image.
