### ISSUE TITLE
Can I use RequestRetrier with this lib?

### ISSUE THREAD

**Issue by felixsolorzano** [Alamofire/AlamofireImage#335]
I'm trying to retry the request whenever an image is not downloaded, is it possible using Alamofire's [RequestRetrier](https://github.com/Alamofire/Alamofire/blob/master/Documentation/Alamofire%204.0%20Migration%20Guide.md#request-retrier)?

**Comment by jshier** [comment]
Yes, you can customize `ImageDownloader` similar to how you would a regular `SessionManager`, including with a `RequestRetrier`.
