### ISSUE TITLE
Compatibility with Alamofire5 branch

### ISSUE THREAD

**Issue by danielemaddaluno** [Alamofire/AlamofireImage#336]
## What did you do?
My pod file contains this:
```
pod 'Alamofire', :git => 'https://github.com/Alamofire/Alamofire.git', :branch => 'alamofire5'
pod 'AlamofireImage', '~> 3.4'
```

## What did you expect to happen?
I know Alamofire5 milestone is not closed, but I just want to know if is there some tricks to make AlamofireImage work in conjuction with Alamofire5 branch.

## What happened instead?
I run `pod install` and got:
```
[!] CocoaPods could not find compatible versions for pod "Alamofire":
  In snapshot (Podfile.lock):
    Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `alamofire5`)

  In Podfile:
    Alamofire (from `https://github.com/Alamofire/Alamofire.git`, branch `alamofire5`)

    AlamofireImage (~> 3.4) was resolved to 3.4.1, which depends on
      Alamofire (~> 4.7)
```

## Alamofire Environment

**Alamofire version:** branch `alamofire5`
**Xcode version:** Version 10.1 (10B61)
**Swift version:** 9.0
**Platform(s) running AlamofireImage:** iOS
**macOS version running Xcode:** Version 10.14.1 (18B75)

**Comment by jshier** [comment]
AlamofireImage 4 is now in beta, and is compatible with Alamofire 5.
