### ISSUE TITLE
Bump to use Alamofire 3.0.0

### ISSUE THREAD

**Issue by AnthonyMDev** [Alamofire/AlamofireImage#34]
@cnoon Now that Alamofire `3.0.0` has been released, would you please push a new version of this library that has a dependency on the stable release?

Thanks!

**Comment by cnoon** [comment]
Thanks for the ping @AnthonyMDev. I was waiting to get #31, #32 and #33 merged before I did so. I just merged the three PRs, and I'll be cutting a new beta today.
