### ISSUE TITLE
Please add Swift 5 support

### ISSUE THREAD

**Issue by OkiRules** [Alamofire/AlamofireImage#343]
Please add Swift 5 support to AlamofireImage.

Thanks!

**Comment by cnoon** [comment]
Working on it, thanks @OkiRules! 🍻

**Comment by cnoon** [comment]
We've just added Xcode 10.2 support in AFI 3.5.1 along with support for the Swift 5 toolset for SPM. While this version of AFI is still building with Swift 4.2, you can absolutely use it with a Swift 5 project. We'll be moving to Swift 5 only in AFI 4.

Cheers. 🍻

**Comment by OkiRules** [comment]
Thanks!
