### ISSUE TITLE
Downloading doesn't work via ImageDownloader

### ISSUE THREAD

**Issue by kafejo** [Alamofire/AlamofireImage#35]
```
let downloader = ImageDownloader()
let URLRequest = NSURLRequest(URL: NSURL(string: "https://httpbin.org/image/jpeg")!)

downloader.downloadImage(URLRequest: URLRequest) { response in
    if let image = response.result.value {
        print(image)
    }
}
```

The completion block isn't even called. Using Alamofire image response serializer works fine.

**Comment by cnoon** [comment]
Your `downloader` is going out of scope. There are MANY [tests](https://github.com/Alamofire/AlamofireImage/blob/master/Tests/ImageDownloaderTests.swift#L118-L256) verifying that the `ImageDownloader` does in fact work.

**Comment by ishaq** [comment]
would it be a good idea to highlight this somewhere in the documentation? I stumbled upon the same bug  just now. while I understand it's programmer's fault here (`downloadImage` being an instance function rather than a static function, so it should imply saving the instance somewhere, correct?). I think since people are used to Alamofire.request (static function), they absent minded expect the same from ImageDownloader.

**Comment by cnoon** [comment]
Would you mind looking through the documentation in the [ImageDownloader Section](https://github.com/Alamofire/AlamofireImage#image-downloader) of the README to give a more specific suggestion on where to provide that info?

**Comment by ishaq** [comment]
sure (in a couple of hours from now), would it be okay if I make the change and send PR?

**Comment by cnoon** [comment]
That would be great!

**Comment by marchy** [comment]
Agreed this is very confusing, and if you follow the documentation it simply doesn't work.
Especially with all the Session/Caching magic, this is definitely NOT expected functionality.

You should add something like "NOTE: The ImageDownloader will cancel all downloads the moment it goes out of scope and no further downloading will take place, so make sure to store it in a scope that matches the lifetime of downloading that you expect (ie: controller, view, service component etc.)"
