### ISSUE TITLE
Incorrect Alamofire dependency on cocoapod spec

### ISSUE THREAD

**Issue by laeroah** [Alamofire/AlamofireImage#354]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

Try install AlamofireImage 3.5.2 via cocoapod and at the same time with a dependency on Alamofire 5.0.0 +

## What did you expect to happen?

Successful install

## What happened instead?

Failed due to conflict requirement on Alamofile version. The [cocoapod spec](https://github.com/CocoaPods/Specs/blob/master/Specs/8/0/a/AlamofireImage/3.5.2/AlamofireImage.podspec.json) on git has not been update to [the latest version](https://github.com/Alamofire/AlamofireImage/blob/master/AlamofireImage.podspec) yet. The Alamofire dependency needs to be updated.

## Alamofire Environment

**Alamofire version:**
**Xcode version:**
**Swift version:**
**Platform(s) running AlamofireImage:**
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by jshier** [comment]
AlamofireImage has a strict dependency on Alamofire. Due to changes in Alamofire 5, AlamofireImage 3 is not compatible. You must update to AlamofireImage 4 (currently 4.0.0-beta.3) to be compatible with Alamofire.
