### ISSUE TITLE
CFBundleShortVersionString has .beta.2 in it

### ISSUE THREAD

**Issue by xGoPox** [Alamofire/AlamofireImage#361]
## What did you do?

Archive then distribute my app to the AppStore

## What did you expect to happen?

to successfully upload my app to the AppStore

## What happened instead?

the ".beta.2" from `CFBundleShortVersionString` key in info.plist still remain in, Apple do not want string in there and the upload fails

## Alamofire Environment

**Alamofire image version: 4.0.0-beta.2**
**Alamofire version: 5.0.0-beta.6**
**Xcode version:**
**Swift version:**
**Platform(s) running AlamofireImage:**
**macOS version running Xcode:**

**Comment by cnoon** [comment]
Thank you for the feedback @xGoPox. We fixed this in Alamofire, but forgot to fix AFI and AFNAI. Would you be able to push up PRs against both repos that drop the `-beta.x` in both Info.plists? Then we could work to get beta releases out for both libraries today.

**Comment by cnoon** [comment]
Closing this out in favor of #359.
