### ISSUE TITLE
URLRequestConvertible disaster

### ISSUE THREAD

**Issue by smhk** [Alamofire/AlamofireImage#366]
The example code on the home page:

```
let downloader = ImageDownloader()
let urlRequest = URLRequest(url: URL(string: "https://httpbin.org/image/jpeg")!)

downloader.download(urlRequest) { response in
    ...
}
```

is unfortunately now totally wrong.

How the heck do you get from a string to a "URLRequestConvertible" ??

thanks so much!

(My aim is simply to prewarm an image.  It's surprising there isn't a prewarm function.  Thanks.)

**Comment by cnoon** [comment]
What version are you using? The docs are out-of-date for the AF5 betas.

**Comment by smhk** [comment]
Thank you,
    github "Alamofire/Alamofire" == 4.7.3
    github "Alamofire/AlamofireImage" == 3.4.1

My `ImageDownloader().download(` accepts only URLRequestConvertible  :-O

**Comment by cnoon** [comment]
I'm not really sure what you're having trouble with. Your sample code you posted compiles and works exactly as you posted. I just dropped this into the `hotfix` branch test suite.

```swift
class ExampleTestCase: XCTestCase {
    func testMe() {
        let downloader = ImageDownloader()
        let urlRequest = URLRequest(url: URL(string: "https://httpbin.org/image/jpeg")!)
        let expect = expectation(description: "testing")

        downloader.download(urlRequest) { response in
            print(response)
            expect.fulfill()
        }

        waitForExpectations(timeout: 5.0, handler: nil)
    }
}
```

`URLRequest` already conforms to `URLRequestConvertible` internally in Alamofire. The reason for having the `URLRequestConvertible` protocol is to allow you to make your own custom types able to be used as well. You can also easily extend String to conform to `URLRequestConvertible` if you really wanted that behavior.

Best of luck! 🍻
