### ISSUE TITLE
identify if a placeholder image is used

### ISSUE THREAD

**Issue by andyyan** [Alamofire/AlamofireImage#37]
We are using af_setImageWithURLRequest to display a profile picture.  Sometimes users don't have a profile picture so we use a placeholderimage instead.  Is there a way to identify if the placeholderimage is  used or not.  Basically I want to set a UI action on profile pictures only but not placeholder images.

**Comment by cnoon** [comment]
You set the placeholder image so you know when it's set. Additionally, you could set the completion closure to know when the actual profile image is set. Everything you need is already there.
