### ISSUE TITLE
af_setImage doesn't work well with iOS 13

### ISSUE THREAD

**Issue by fabios9702** [Alamofire/AlamofireImage#370]
## What did you do?

I'm having problems with Alamofire image with iOS 13, some images are loaded and placed, but other not. Is this a known problem with iOS 13? How can I fix it?

## Alamofire Environment

**Alamofire version: 4.8.2
**Alamofire Image version: 3.5.2
**Xcode version: 11
**Swift version: 4
**Platform(s) running AlamofireImage: iOS 13
**macOS version running Xcode:**

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by Tequilag** [comment]
Same problem
**Alamofire version: 4.8.2
**AlamofireImage version: 3.5.0
**Xcode version: 11
**Swift version: 5
**Platform(s) running AlamofireImage: iOS 13

**Comment by albertolina** [comment]
Same problem. iOS 13 is releasing in a couple of weeks and our app is totally unusable due to this issue. We either need to stop using AlamofireImage or someone needs to give us more info.

Thank you very much

**Alamofire version: 4.8.2
**Alamofire Image version: 3.5.2
**Xcode version: 11
**Swift version: 4
**Platform(s) running AlamofireImage: iOS 13

**Comment by jshier** [comment]
All of our tests and demo project are working fine on iOS 13, so please provide additional information and, most helpfully, a demo project that reproduces the issue in the simulator. 

This includes:
- Any errors seen.
- Kinds of images which sometimes don't load.
- Any customizations you've made to the default `ImageDownloader` instance. 
- Code samples showing how you use `af_setImage`.

You should also be retesting on the new betas as you go, as this year's beta process has been particularly buggy.

**Comment by fabios9702** [comment]
Are you testing with iOS 13 SDK? Because the App developed for iOS 13 in Xcode 11 doesn't work well with Alamofire, instead, the same app that is already on the store for iOS 11 or superior, works fine.
We've have not customised the `ImageDownloader` istance;

sample of code using af_setImage:
`imageToPlace.af_setImage(withURL: URL(string: artworkImage)!)`

The images are all .jpg or .png, furthermore there are no errors or warnings. There isn't a rule that make the images not loading, for example, sometimes it doesn't load the heavy images and sometimes it doesn't load the lights images.
We've have also checked the urls that are passed to `af_setImage` and they are valid

**Comment by jshier** [comment]
Yes, the testing was performed with Xcode 11 beta 6 on the iOS 13 simulator. 

If you could perform some investigation on your side to narrow down why images might not be showing up, we could think investigate a fix. It could be a few things:

- It's not actually downloading the image.
- The image is downloaded, but is never rendered.
- It's rendered but never appears in the image view.

Answering those questions would help narrow down a fix.

**Comment by fabios9702** [comment]
I've tried and I found that this part of code in the af_setImage function is never called

```
 // Generate a unique download id to check whether the active request has changed while downloading
        let downloadID = UUID().uuidString

        // Download the image, then run the image transition or completion handler
        let requestReceipt = imageDownloader.download(
            urlRequest,
            receiptID: downloadID,
            filter: filter,
            progress: progress,
            progressQueue: progressQueue,
            completion: { [weak self] response in
                guard
                    let strongSelf = self,
                    strongSelf.isURLRequestURLEqualToActiveRequestURL(response.request) &&
                    strongSelf.af_activeRequestReceipt?.receiptID == downloadID
                else {
                    completion?(response)
                    return
                }

                if let image = response.result.value {
                    strongSelf.run(imageTransition, with: image)
                }

                strongSelf.af_activeRequestReceipt = nil

                completion?(response)
            }
        )
```

**Comment by jshier** [comment]
Where does it return before then? From the initial `guard`, or the cache check?

**Comment by fabios9702** [comment]
sometimes, after `let downloadID = UUID().uuidString`, it goes directly to `af_activeRequestReceipt = requestReceipt`, sometimes it stops at` let downloadID = UUID().uuidString` without returning anything

**Comment by jshier** [comment]
That doesn't make much sense. Are you building with optimization?

**Comment by fabios9702** [comment]
yes, it's stetted to Optimize for speed [-O]

**Comment by jshier** [comment]
Please turn that off and test again, as it prevent breakpoints from working correctly.

**Comment by fabios9702** [comment]
I turnet all the optimizations to No Optimization, but it doesn't work anyway

**Comment by jshier** [comment]
Right, but you should now be able to trace the path more accurately.

**Comment by fabios9702** [comment]
ok, now it enter in the code and the `response.result.value` is nil, so it doesn't run  `strongSelf.run(imageTransition, with: image)`

**Comment by jshier** [comment]
Right. You should be able to check the `response` in that closure and make sure it has the appropriate response code, data, etc.

**Comment by fabios9702** [comment]
if I do a` po response` when I put the breakpoint the result is 
```
error: Couldn't materialize: can't get size of type
error: errored out in DoExecute, couldn't PrepareToExecuteJITExpression
```

**Comment by jshier** [comment]
Yes, you must turn off optimizations for debugging to work correctly.

**Comment by fabios9702** [comment]
it's off

**Comment by jshier** [comment]
There are other settings that can interfere with debugging. At this point this doesn't look like an AlamofireImage bug. Please continue debugging until you discover the cause, and if it is a bug, please comment and I can reopen the issue.

**Comment by ckakei** [comment]
In my case, I add support to the "application/octet-stream" into the acceptableImageContentTypes fix my problem 

`DataRequest.addAcceptableImageContentTypes(["application/octet-stream"])`

**Comment by tomeron11** [comment]
Hi
also have the same problem. the af_setImage cause my app to crash.
in xcode 10 it worked fine. also after i updated my iphone to ios13
with xcode11 (official) it crashes.
the debugger points on 
public static func af_threadSafeImage(with data: Data, scale: CGFloat) -> UIImage? {
        lock.lock()
        **let image = UIImage(data: data, scale: scale)**
        lock.unlock()
        return image
    }

and in the console i see
seek:285: *** IIOScanner::seek reached EOF
getVal16:139: *** IIOScanner::getVal16 reached EOF


i tried the octet-stream from previous comment. didn't help

**Comment by carlosh** [comment]
> In my case, I add support to the "application/octet-stream" into the acceptableImageContentTypes fix my problem
> 
> `DataRequest.addAcceptableImageContentTypes(["application/octet-stream"])`
> 
> In iOS 13 Release note have the following statement:
> 
> To enhance security, URLSession no longer sniffs the MIME type when the server sends Content-Type: application/octet-stream. (7820658)
> 
> https://developer.apple.com/documentation/ios_ipados_release_notes/ios_13_release_notes

I found myself having this issue when I recently upgraded to Xcode 11. I can confirm the above was the actual issue, and adding the image content type fixed it for me. Not sure if ImageDownloader should have a default configuration for this, or the developer should always need to add this image content type. Either way, I feel it should be explained in the readme file. Thanks.

**Comment by rafaelc0sta** [comment]
@jshier Hey, I believe @carlosh is right... can you reopen the issue?

**Comment by cnoon** [comment]
We've added the `application/octet-stream` content type in f48f8cfe. It will be released shortly as part of AFI 4.0.0.

Cheers. 🍻

**Comment by ReflectCode** [comment]
This is just for record and may help other developers in future. 
The AWS S3 server we were connecting to download images was sending content type "image/*" and AF was throwing error. 
We could get around this problem by using '**ImageResponseSerializer**' : 
```
 var imgSer = ImageResponseSerializer.self
        imgSer.addAcceptableImageContentTypes(Set(arrayLiteral: "image/*"))
        mView!.af.setImage( withURL: url, 
                placeholderImage: mPlaceholderImage, 
                **serializer: imgSer.init()**, 
                filter: self, 
                progress: nil,  imageTransition: imgTransition!, runImageTransitionIfCached: true, completion: { dr in  .....
```

AlamofireImage (3.6.0), Alamofire (4.9.1)

**Comment by shreyadc** [comment]
I faced this issue(even in iOS 15, AlamofireImage 4.2.0). I was using af.setImage to download and set images. The images were perfectly downloading from every url, other than the images in aws s3 bucket. The s3 bucket images weren't downloading and displaying properly.
After much debugging, I see that following are the acceptable content types in AFI. 
acceptableContentTypes: ["application/octet-stream", "image/bmp", "image/gif", "image/heic", "image/heif", "image/ico", "image/jp2", "image/jpeg", "image/jpg", "image/png", "image/tiff", "image/webp", "image/x-bmp", "image/x-icon", "image/x-ms-bmp", "image/x-win-bitmap", "image/x-xbitmap"]

But the images in s3 have response content type "binary/octet-stream", so although the images are downloading perfectly and can be further retrieved from response data, they're getting AlamofireImage.AFIError.alamofireError(Alamofire.AFError.responseValidationFailed(reason: Alamofire.AFError.ResponseValidationFailureReason.unacceptableContentType(..)) and so they are unable to set in the imageview.

AFAIK AFI should include "binary/octet-stream" in the acceptable content-type as well!

**Comment by keegho** [comment]
@shreyadc 

Yes had same issue and I solved it this way

`import AlamofireImage    

ImageResponseSerializer.addAcceptableImageContentTypes(["image/jpg"])`

**Comment by jshier** [comment]
AlamofireImage 4.2.0 should have both `application/octet-stream` and `image/jpg` in the default `Accept` header.
