### ISSUE TITLE
Generic type 'DataResponse'  error with Xcode 11 beta 6

### ISSUE THREAD

**Issue by hurtic** [Alamofire/AlamofireImage#374]
I'm getting the following compiler error when using "4.0.0-beta.4" with Xcode 11 beta 6:

"Generic type 'DataResponse' specialized with too few type parameters (got 1, but expected 2)"

**Comment by jshier** [comment]
Yes, you shouldn't update to Alamofire 5 RC1 yet, as we need to update AlamofireImage as well.

**Comment by hurtic** [comment]
Oh, I missed that one. Thanks!

**Comment by jshier** [comment]
These changes are now in `master` and will go out as part of a beta soon.

**Comment by rohitnatraj** [comment]
@jshier - Has this been released in the beta?

**Comment by jshier** [comment]
Not yet, I'll do a release tonight.

**Comment by rohitnatraj** [comment]
Cool, Thank you.

**Comment by iur-kaia** [comment]
@jshier sorry to poke you on this closed thread but I have the same issue on Xcode 11.6 when I try to build AlamofireImage with Carthage. Is the issue back? Any pointers?

```
/proj-path/Carthage/Checkouts/AlamofireImage/Source/ImageDownloader.swift:35:39: error: generic type 'DataResponse' specialized w
ith too many type parameters (got 2, but expected 1)
public typealias AFIDataResponse<T> = DataResponse<T, AFIError>
                                      ^           ~~~~~~~~~~~~~
Alamofire.DataResponse:1:15: note: generic type 'DataResponse' declared here
public struct DataResponse<Value> {
              ^
/proj-path/Carthage/Checkouts/AlamofireImage/Source/ImageDownloader.swift:38:33: error: generic type 'Result' specialized with to
o many type parameters (got 2, but expected 1)
public typealias AFIResult<T> = Result<T, AFIError>
                                ^     ~~~~~~~~~~~~~
Alamofire.Result:1:13: note: generic type 'Result' declared here
public enum Result<Value> {
            ^
/proj-path/Carthage/Checkouts/AlamofireImage/Source/Request+AlamofireImage.swift:37:45: error: use of undeclared type 'ResponseSerializer'
public final class ImageResponseSerializer: ResponseSerializer {
                                            ^~~~~~~~~~~~~~~~~~
/proj-path/Carthage/Checkouts/AlamofireImage/Source/ImageDownloader.swift:112:25: error: use of undeclared type 'Session'
    public let session: Session
                        ^~~~~~~

```

**Comment by jshier** [comment]
@iur-kaia You need to update your Carthage checkouts for the latest version. Make sure you follow Carthage's directions for a clean build.

**Comment by iur-kaia** [comment]
@jshier thanks for the quick and helpful response. 
Indeed, deleting Carthage checkout and build directory in my project and running `carthage bootstrap` again to refetch libs has fixed the build. 
I didn't have to completely clean Carthage cache.
