### ISSUE TITLE
Using a singleton sessionManager in ImageDownloader breaks that sessionManager

### ISSUE THREAD

**Issue by rausnitz** [Alamofire/AlamofireImage#379]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

We have the following extension of UIImageView...
```
extension UIImageView {
    func setImage(withURL url: URL) {
        self.af_imageDownloader = ImageDownloader(sessionManager: DataFetcher.shared)
        self.af_setImage(withURL: url)
    }
}
```
...which uses a singleton session manager that looks basically like this...
```
class DataFetcher: AlamoFire.SessionManager {
      static let shared = DataFetcher()
}
```

We use the `setImage(withURL:)` function to download and cache some images in our app. The same session manager singleton is used for various other HTTP requests elsewhere in our app.

## What did you expect to happen?

We expected `setImage(withURL:)` to work without affecting other requests that use the `DataFetcher.shared` singleton.

## What happened instead?

After calling `setImage(withURL:)`, other requests sent through `DataFetcher.shared` stop getting called. We can solve this problem by providing a new `DataFetcher()` instance to `ImageDownloader()` instead of the singleton. That solves the problem, but if this is unexpected behavior for AlamofireImage, it might be a bug somewhere.

## Alamofire Environment

**Alamofire version:**
```
- Alamofire (4.7.3)
 - AlamofireImage (3.4.1):
   - Alamofire (~> 4.7)
```
**Xcode version:**
10.2.1
**Swift version:**
5.0.1
**Platform(s) running AlamofireImage:**
iOS
**macOS version running Xcode:**
10.14.5

**Comment by jshier** [comment]
Unfortunately this is an inherent limitation of AlamofireImage: all `SessionManager`s passed to AlamofireImage must have `startRequestsImmediately = false`, meaning all other usage with that `SessionManager` must call `resume()` to start their requests. Your solution of a separate `SessionManager` for image downloading vs. API usage also works.

**Comment by rausnitz** [comment]
For future reference for anyone encountering this issue - it looks like Alamofire 5 prevents it by requiring `startRequestsImmediately` to be false in an `ImageDownloader`'s session. Here's the change: https://github.com/Alamofire/AlamofireImage/commit/4ac1345d8249cec4eddd087a5a12411b1d7f939f#diff-2164d1f2f5cdab9b4f6bdcdeecd615fcR199

**Comment by gbejarano01** [comment]
@rausnitz I saw that change, and I'm seeing that even setting the `startRequestsImmediately`to `false` is making the precondition to fail.

This is a closed issue, not sure if this would help, but I was wondering if you got this solved.
