### ISSUE TITLE
Image fails to load after device locked

### ISSUE THREAD

**Issue by drichardson** [Alamofire/AlamofireImage#38]
When I lock my device (iPhone 6 iOS 9.0.2, AlamofireImage 2.0.0), I noticed that the first time I call `af_setImageWithURL` on a `UIImageView` the first image consistently does not load (if the image is not already cached). I believe this is due to Alamofire/Alamofire#872.

I was able to workaround the issue with the following code (which I'm not suggesting as a fix but I think shows it's the same underlying issue as Alamofire/Alamofire#872):

    func applicationWillEnterForeground(application: UIApplication) {
        UIImageView.af_sharedImageDownloader = ImageDownloader()
    }

**Comment by cnoon** [comment]
I'm going to close this issue out since the conversation took place in the [Alamofire #872](https://github.com/Alamofire/Alamofire/issues/872) issue.
