### ISSUE TITLE
init(memoryCapacity:diskCapacity:diskPath:)' is unavailable in UIKit for Mac 

### ISSUE THREAD

**Issue by umairxiq** [Alamofire/AlamofireImage#381]
Using latest Xcode 11.0 building for mac I get the following build error:

init(memoryCapacity:diskCapacity:diskPath:)' is unavailable in UIKit for Mac

Would be awesome if that could be fixed!

**Comment by jshier** [comment]
This has been updated for the 4.0.0 beta series, but not the 3.x series. I'll see if we can backport the changes and release it soon.

**Comment by jshier** [comment]
This has now been released as part of 3.6.0.
