### ISSUE TITLE
Multithreaded reader writers issue with ImageCache module

### ISSUE THREAD

**Issue by eSpecialized** [Alamofire/AlamofireImage#382]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

ImageCache module was found removing images from the cache concurrently.  This occasionally causes crashing in our Application when the cache approaches a full state.
	Any add/remove actions should be wrapped under the synchronizationQueue with the **barrier** option.

## What did you expect to happen?

ImageCache should function without issue.

## What happened instead?

ImageCache crashes once cache fills on occasion.

## Alamofire Environment

Alamofire version: 
  - Alamofire (5.0.0-beta.7)
  - AlamofireImage (4.0.0-beta.4):
Xcode 11
Swift 5
Platform(s) running AlamofireImage: iOS
**macOS version running Xcode: Mojave

## Demo Project
   None provided.

Modifying any imageCache test to use multiple DispatchQueue’s to add/remove from the imageCache will present the crash bug.
	Notes: It should add/remove 100’s of times if not 1000’s, and surpass the cache Limit many times to cause the bug to present.

**Comment by jshier** [comment]
This has been fixed in #387 and will be released as 4.0.0-beta.6.
