### ISSUE TITLE
AlamofireImage installed from CocoaPods

### ISSUE THREAD

**Issue by alejandroivan** [Alamofire/AlamofireImage#400]
File `UIImage+AlamofireImage.swift` makes the whole module uncompilable.
Basically because, on line 385, it's missing a `return` statement.
Leaving that line like this fixes all issues:

`return af.imageFiltered(withCoreImageFilter: name, parameters: parameters)`

**Comment by jshier** [comment]
Looks like we missed a Swift 5 compatibility issue. Working on a release now, it should be available soon.

**Comment by jshier** [comment]
This should be fixed now, feel free to update to 4.0.1.
