### ISSUE TITLE
Does AlmofireImage uses UIWebview?

### ISSUE THREAD

**Issue by anoopkashok** [Alamofire/AlamofireImage#411]
I am using AlamofireImage(3.6.0) in one of my projects. I integrated using carthage dependency manager. The problem is when I run command ( grep -r UIWebView . ) in my project directory, AlamofireImage image library showing one of the library which uses UIWebview. Is there any fixes for this in updated release or any release plan soon. I am worried about app store rejection due to UIWebview usage.

**Comment by jshier** [comment]
No, no Alamofire library uses `UIWebView`.
