### ISSUE TITLE
Carthage installation fails for version 4.0.3

### ISSUE THREAD

**Issue by ale84** [Alamofire/AlamofireImage#412]
I am using Carthage v. 0.34.0
Carthage build fails with the following error:

```
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/alessio/Developer/Work/stah_events_ios/Carthage/Checkouts/AlamofireImage/AlamofireImage.xcworkspace -scheme AlamofireImage\ iOS -configuration Release -derivedDataPath /Users/alessio/Library/Caches/org.carthage.CarthageKit/DerivedData/11.3.1_11C504/AlamofireImage/4.0.3 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/w8/yzws0hcx499dt6n92fd_8bdm0000gn/T/AlamofireImage SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/alessio/Developer/Work/stah_events_ios/Carthage/Checkouts/AlamofireImage)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/w8/yzws0hcx499dt6n92fd_8bdm0000gn/T/carthage-xcodebuild.4B7wZb.log
```

## Alamofire Environment

**Alamofire version:**  5.0.5
**Xcode version:** 11.3.1
**Swift version:** 5
**Platform(s) running AlamofireImage:** iOS
**macOS version running Xcode:** 10.15.3

**Comment by jawi-bq** [comment]
I just had the same issue (updating project to xcode 11.4 & alamofire 5.0.5) and manually removing Carthage/Checkouts/AlamofireImage solved it.

**Comment by ale84** [comment]
> I just had the same issue (updating project to xcode 11.4 & alamofire 5.0.5) and manually removing Carthage/Checkouts/AlamofireImage solved it.

it works thank you.

**Comment by mbuchetics** [comment]
what do you mean by removing the folder? how do you build it if you removed the checkout folder?

**Comment by jawi-bq** [comment]
Of course to compile the project I had to to rebuild checkouts by `carthage update AlamofireImage` ;)

**Comment by jshier** [comment]
We've recently removed our submodule Carthage checkout of Alamofire, so Carthage users will need to redo their checkout of AlamofireImage to capture Alamofire locally.
