### ISSUE TITLE
Support to build xcframework

### ISSUE THREAD

**Issue by cuongtv51** [Alamofire/AlamofireImage#416]
As i know, Swift 5.1 has support create xcframework.
Can we have option or guideline to build xcframework?
It will help reduce steps for integrate into project.

**Comment by jshier** [comment]
As XCFrameworks require the use of library evolution mode, which we don't support (nor does Alamofire), we won't be supporting such builds for AlamofireImage either. If that changes, we'll provide directions for all Alamofire libraries.
