### ISSUE TITLE
Images not loading from an IP URL

### ISSUE THREAD

**Issue by nyeu** [Alamofire/AlamofireImage#420]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

Images from an insecure network are not loading. I am using a dev environment based on an ip (not a domain) - http://15.XXX.XX.XX:8180 - and image loading timeout. If I change that to any other URL it works. I have also tried to open http://15.XXX.XX.XX:8180/image.jpg in the browser and it works.

I have `Allow Arbitrary Loads` set to `YES` in my Info.plist.

## What did you expect to happen?

I would expect the image to load and be visible.

## What happened instead?

The request times out. 

## Alamofire Environment

**Alamofire version:**
**Xcode version:** 11.3
**Swift version:** 4.2
**Platform(s) running AlamofireImage:** iOS 13.2 - my own device iPhone 11 Pro
**macOS version running Xcode:** 10.14.6

This is a URL where it fails: `http://15.185.41.76:9090/fitcash/products/3805ec1b-623f-4eac-8d4c-5282e0aca0ee/picture_name_1.jpeg`

**Comment by jshier** [comment]
This seems like a local networking issue, so I'd suggest looking into solutions on StackOverflow.
