### ISSUE TITLE
Xcode 12 Beta Archive issue 

### ISSUE THREAD

**Issue by cassianodialpad** [Alamofire/AlamofireImage#422]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

Same issue as reported here: https://github.com/Alamofire/Alamofire/issues/3240

## What did you do?

Tried to build AlamofireImage with carthage.

## What did you expect to happen?

Build sucessful.

## What happened instead?

Archive failed with error:

`Undefined symbols for architecture armv7:
  "type metadata for Swift._StringObject.Variant", referenced from:
      outlined init with take of Swift._StringObject.Variant in ParameterEncoding.o
ld: symbol(s) not found for architecture armv7`

## Alamofire Environment

**Alamofire version:** 5.2.2, then the hotfix from "tattn/Alamofire" "hotfix-xcode12" as described here: https://github.com/Alamofire/Alamofire/issues/3240
**AlamofireImage version:** 4.1.0
**Xcode version:** 12 beta 2
**Swift version:** 5.3
**Platform(s) running AlamofireImage:** iOS
**macOS version running Xcode:** 10.15.6

**Comment by LamourBt** [comment]
I'm having this issue as well.

**Comment by jshier** [comment]
This should be fixed by Xcode 12b4.

**Comment by jbarros35** [comment]
final release updated on the App Store, not beta.
does not compile. was before running.
