### ISSUE TITLE
Carthage build error with Xcode 12

### ISSUE THREAD

**Issue by soareseneves** [Alamofire/AlamofireImage#427]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

Updated Xcode to version 12.0 GM, updated my cart file with Alamofire and AlamofireImage latest version, removed Xcode DerivedData and Carthage DerivedData as well, ran: ./carthage-build.sh update --platform iOS --no-use-binaries according to this: https://github.com/Carthage/Carthage/issues/3019#issuecomment-693381253

## What did you expect to happen?

A successful build.

## What happened instead?

Got this error: Building scheme "AlamofireImage iOS" in AlamofireImage.xcworkspace
Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -workspace /Users/douglas/Documents/Development/SigiWebiOS/Carthage/Checkouts/AlamofireImage/AlamofireImage.xcworkspace -scheme AlamofireImage\ iOS -configuration Release -derivedDataPath /Users/douglas/Library/Caches/org.carthage.CarthageKit/DerivedData/12.0_12A7209/AlamofireImage/4.1.0 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/16/q0qvn3dj6416pvscl994q9br0000gn/T/AlamofireImage SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /Users/douglas/Documents/Development/SigiWebiOS/Carthage/Checkouts/AlamofireImage)

This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/16/q0qvn3dj6416pvscl994q9br0000gn/T/carthage-xcodebuild.LUteXn.log

Here is the log file: https://pastebin.com/H1eCDvtT

## Alamofire Environment

**Alamofire version:** 4.1
**Xcode version:** 12.0 GM
**Swift version:** 5.3
**Platform(s) running AlamofireImage:** iOS
**macOS version running Xcode:** Catalina

**Comment by jshier** [comment]
Carthage is currently having issues with Xcode 12. Additionally, you should update to the latest Alamofire, 4.1 is very old.

**Comment by RajaveluC** [comment]
I just had the same issue. Manually removing Carthage/Checkouts/AlamofireImage and running "./carthage.sh update AlamofireImage --platform iOS" solved it.
