### ISSUE TITLE
IPHONEOS_DEPLOYMENT_TARGET is set to 8.0 but Xcode 12 does't support it anymore

### ISSUE THREAD

**Issue by romeugodoi** [Alamofire/AlamofireImage#431]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

ℹ The version 3.6.0 is causing an error, and can't be built on Xcode 12.*, cos the IPHONEOS_DEPLOYMENT_TARGET 8.0 is not supported anymore. And in case using this version in projects already in production that is so expensive to upgrade it as I've one, we could fix it.

## What did you expect to happen?

ℹ To Built successful 

## What happened instead?

ℹ The Crash error: "The package product 'Alamofire' requires minimum platform version 9.0 for the iOS platform, but this target supports 8.0"
<img width="340" alt="image" src="https://user-images.githubusercontent.com/556442/99157850-7ccced00-26ab-11eb-863f-55c9bdf6e9aa.png">

## Alamofire Environment

**AlamofireImage version:** 3.6.0 
**Xcode version:** 12.2
**Swift version:** 5
**Platform(s) running AlamofireImage:** SPM
**macOS version running Xcode:** 11.0.1

**Comment by jshier** [comment]
Please update to version 4.1 to fix this issue. There will be no additional updates to version 3.
