### ISSUE TITLE
Crash on af.setImage

### ISSUE THREAD

**Issue by Azeoo-Loris** [Alamofire/AlamofireImage#436]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

implementation of setImage method in UIImageView subclass 

![image](https://user-images.githubusercontent.com/61061236/103246422-aa23e080-4963-11eb-9228-f820a70222b4.png)

## What did you expect to happen?

Image is downloaded and displayed on the UIImage  

## What happened instead?

Crash on Alamofire Session init Class  

![image](https://user-images.githubusercontent.com/61061236/103246454-c162ce00-4963-11eb-88d2-b6baf5065075.png)

## Alamofire Environment

**AlamofireImage version: 4.1.0
**Alamofire version: 5.4.1
**Xcode version: 12.3
**Swift version: 5.3
**Platform(s) running AlamofireImage: Ios
**macOS version running Xcode: Catalina 10.15.4

## Demo Project

ℹ Please link to or upload a project we can download that reproduces the issue.

**Comment by armarpc** [comment]
I was using Carthage for including both Alamofire and AlamofireImage and was experiencing this issue. I solved it by removing both frameworks from Carthage and including AlamofireImage in my project through Swift Package Manager.
![Screen Shot 2021-02-10 at 2 03 14 PM](https://user-images.githubusercontent.com/5358945/107551852-276c8300-6ba9-11eb-85d5-e26275122ee7.png)

**Comment by sloik** [comment]
Same thing when using Carthage.

**Comment by jshier** [comment]
This appears to be a runtime issue, not specifically AFI related.
