### ISSUE TITLE
how can I achieve an AutoPurgingImageCache with unlimited size?

### ISSUE THREAD

**Issue by Ita-Manor** [Alamofire/AlamofireImage#445]
how can I achieve an AutoPurgingImageCache with unlimited size?

what would happen if I - 
let imageCache = AutoPurgingImageCache(memoryCapacity: 0, preferredMemoryUsageAfterPurge: 0)

**Comment by jshier** [comment]
There's no support for unlimited size. Such usage would inevitably crash your app as the system ran out of memory, at least on iOS and associated OSes.
