### ISSUE TITLE
Fix Package.swift and release 3.5.3 for older version use via SPM

### ISSUE THREAD

**Issue by timshadel** [Alamofire/AlamofireImage#447]
* [X] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

I relied on AlamofireImage 3.5.2 in my project, via SPM.

## What did you expect to happen?

I expected it to compile, since it did so using Cocoapods previously.

## What happened instead?

Swift Package Manager said that the version of Alamofire listed allows iOS 9, but AlamofireImage allows iOS 8. The project could not be built.

## Resolution

In a [fork I changed the Package.swift](https://github.com/timshadel/AlamofireImage/commit/8b3cbf527537858a61c12becb751f536356b05d8) to have iOS 9 as the minimum version. It all worked perfectly.

Please create a simple branch for this change, tag it as 3.5.3, and then delete the branch. It will significantly help those of us using SPM. Thanks!

**Comment by jshier** [comment]
Won't be fixing things like this, as Xcode will keep bumping the minimum and we don't want to update every older version every time that happens. Feel free to fork if you really need it but updating to the latest version is the proper fix.
