### ISSUE TITLE
Image is not cashing if we download image using ImageDownloader and restart the application

### ISSUE THREAD

**Issue by Tarun2381993** [Alamofire/AlamofireImage#457]
Alamofire Version: 4.2.0
Xcode Version: 13.2.1
Swift Version: 5

--> Created Image downloaded instance using below inputs,

```
ImageDownloader(
            configuration: .default,
            downloadPrioritization: .fifo,
            maximumActiveDownloads: 4,
            imageCache:AutoPurgingImageCache()
        )
```

--> Started download image process with below function.

```
imageLoader.download(urlRequest,
                             cacheKey: "test_cacheKey",
                             filter: nil,
                             progressQueue: .main,
                             completion:  { response in
        //response
}
```

**Problem** 
-> I am trying to load image in SwiftUI View.
-> Internet is on and open the application.
-> I download the image and showed in UI (Image downloaded successfully and it's visible in UX)
-> Now kill the application, turn off the internet and relaunch the app.
-> Again call the download call but it's failing.
-> Expected result: it showed return image from local cache.

Please Help!!

**Comment by Tarun2381993** [comment]
@jshier is it something am I missing from my end for supporting cache if we restart the app?

**Comment by jshier** [comment]
AlamofireImage doesn't currently have a persistent caching mechanism other than `URLCache`'s disk storage, so if your image responses aren't cached at that level, there will be no persistence. This is a well known feature request.
