### ISSUE TITLE
Feature request: Support `image/avif` to Accept header for iOS 16, macOS Ventura and more.

### ISSUE THREAD

**Issue by r-plus** [Alamofire/AlamofireImage#461]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

## What did you do?

iOS 16 and macOS Ventura start support AVIF image type so this feature request want adding `image/avif` to request Accept header as dynamic similar to `image/webp` support.

- https://github.com/Alamofire/AlamofireImage/pull/434
- https://caniuse.com/avif

I'm not sure about tvOS and watchOS are support AVIF on latest version.

## What did you expect to happen?

`image/avif` string contained in accept header when running OS is iOS 16 or macOS Ventura.

## What happened instead?

Not yet added.

## Alamofire Environment

Alamofire Image version: 4.2.0

## Demo Project

N/A

**Comment by jshier** [comment]
Makes sense, I can investigate soon. Can you (or anyone) confirm whether AVIF decoding is exposed to `UIImage` / `NSImage` / `CGImage` and on what platforms? WebP was weird because only iOS / macOS supported it and tvOS / watchOS didn't.

**Comment by r-plus** [comment]
I just try to show AVIF basic image (YUV420, 8bit depth) from https://github.com/link-u/avif-sample-images by this code.
It displayed hato image on iOS 16.0.3, iPhone 14 Pro device.

```swift
struct ContentView: View {
    var body: some View {
        let url = URL(string: "https://raw.githubusercontent.com/link-u/avif-sample-images/master/hato.profile0.8bpc.yuv420.avif")!
        AsyncImage(url: url) { image in
            image.resizable()
                .scaledToFit()
        } placeholder: {
            ProgressView()
        }
    }
}
```

additionally, check the `UIImage` too.

```swift
    override func viewDidLoad() {
        super.viewDidLoad()
        let url = URL(string: "https://raw.githubusercontent.com/link-u/avif-sample-images/master/hato.profile0.8bpc.yuv420.avif")!
        let v = UIImageView(frame: .init(x: 0, y: 0, width: 300, height: 300))
        self.view.addSubview(v)
        Task {
            let result = try! await URLSession.shared.data(for: URLRequest(url: url))
            let image = UIImage.init(data: result.0)!
            v.image = image
        }
    }
```

not yet upgrade to macOS Ventura to check this.

**Comment by r-plus** [comment]
`SwiftUI` and `NSImage` correctly displayed avif image on macOS Ventura.

`SwiftUI`
<img width="741" alt="スクリーンショット 2022-10-28 22 47 28" src="https://user-images.githubusercontent.com/425216/198624222-f106e433-71f7-4ab8-890b-7e6662181f3c.png">

`NSView`
<img width="883" alt="スクリーンショット 2022-10-28 22 50 48" src="https://user-images.githubusercontent.com/425216/198624322-128d112e-ba15-4bc7-947e-4482d543d332.png">

**Comment by jshier** [comment]
Looks like AVIF is supported on macOS, iOS, and tvOS (unlike WebP still), but not watchOS. I've got the change but I need to update and deploy a new version of the test server along with a significant testing refactor for the new OSes.

**Comment by jshier** [comment]
Sorry for the long delay. This has been merged, along with JPEG XL support on the 2023 OSes, in #464 and should go out with the next release.
