### ISSUE TITLE
App crash on ios 11.0.2, xcode 14.0.1

### ISSUE THREAD

**Issue by Hudayberdyyev** [Alamofire/AlamofireImage#462]
## What did you do?

ℹ I run my app on xcode 14.0.1. iOS version 11.0.2

## What did you expect to happen?

ℹ My app should run without problems

## What happened instead?

ℹ My app is crashed. There is logs: Library not loaded: /usr/lib/swift/libswiftCoreGraphics.dylib

## Alamofire Environment

**Alamofire version: 5.2**
**AlamofireImage version: 4.1**
**Xcode version:14.0.1**
**Swift version:5**
**Platform(s) running AlamofireImage:iOS 11.0.2**
**macOS version running Xcode:Ventura 13.0 (22A380)**

## Demo Project

ℹ I can't provide you with a link to the repository. but I can show you my Podfile where I import this library.
pod 'AlamofireImage', '~> 4.1'

**Comment by jshier** [comment]
Seems like an ephemeral linking issue with the CoreGraphics Swift overlay, so not an AFI issue. Feel free to open a new issue if it reoccurs.
