### ISSUE TITLE
Does AlamofireImage support resizing animated GIF?

### ISSUE THREAD

**Issue by Jeanno** [Alamofire/AlamofireImage#463]
Someone recommended me to use AlamofireImage for this purpose. But after reading some of the documentation, there's no words on whether or not the `UIImage` or `Scaling` work for animated GIFs.

Specifically I would like to use this method for scaling animated GIFs. https://alamofire.github.io/AlamofireImage/Extensions/UIImage.html#/s:So7UIImageC14AlamofireImageE20af_imageAspectScaled5toFit5scaleABSo6CGSizeV_12CoreGraphics7CGFloatVSgtF

Thanks.

**Comment by jshier** [comment]
There's no special support for resizing animated gifs, just whatever is supported by the system image resizing in general.
