### ISSUE TITLE
Apple Privacy Manifest

### ISSUE THREAD

**Issue by carlosasmartins** [Alamofire/AlamofireImage#473]
* [x] I've read, understood, and done my best to follow the [*CONTRIBUTING guidelines](https://github.com/Alamofire/AlamofireImage/blob/master/CONTRIBUTING.md).

Apple is enforcing privacy manifests by Spring 2024, is this something on your radar? 🙏 
https://developer.apple.com/news/?id=r1henawx

**Comment by isthisjoe** [comment]
+1

**Comment by cbiggin** [comment]
Alamofire is specifically listed as needing a privacy manifest: https://developer.apple.com/support/third-party-SDK-requirements/

**Comment by jshier** [comment]
Alamofire has an open PR to add one, pending more confirmation from Apple about what exactly is needed. https://github.com/Alamofire/Alamofire/pull/3792 AlamofireImage doesn't use any of the limited APIs and so shouldn't need one at all.

**Comment by mejim707** [comment]
@jshier Do you have confirmation from Apple that Alamofirelmage will not require this Manifest and will not include it? If so, I will cross this dependency off my list.

Thanks

**Comment by carlosasmartins** [comment]
Since the PR is now merged will we have a release soon? 🙏

**Comment by mejim707** [comment]
If the SDK does not share user tracking details, does this actually require the update? We will update to the latest version regardless, but I'm interested in your insight here. 

Thanks

**Comment by jshier** [comment]
AlamofireImage shouldn't need its own manifest, as it doesn't use any of the newly restricted APIs (no Alamofire framework collects data of any sort). It should just inherit Alamofire's privacy policy automatically without update.

**Comment by mejim707** [comment]
@jshier Excellent thank you for the fast reply. I will mark this SDK down as it's not required to include the manifest! Great news there.

**Comment by jshier** [comment]
Alamofire's privacy manifest shipped with 5.9.0, make sure to update.

**Comment by carlosasmartins** [comment]
My reasoning is that if Alamofire is included in the list of privacy manifest requiring SDK's and AlamofireImage is depending on Alamofire then Alamofire needs to include the privacy manifest and AlamofireImage needs to point to that updated version as well.

Now I guess it depends on how deep into child's dependencies the Apple scanning goes 😅
