### ISSUE TITLE
Request for updated iOS SDK version with the xcprivacy manifest

### ISSUE THREAD

**Issue by sakshibala-halodoc** [Alamofire/AlamofireImage#475]
Subject: We need to incorporate the xcprivacy manifest into our app . Starting March 13, Apple will send notifications when uploading builds to the App Store, and this will become mandatory from May 1. All the SDKs used in our app needs to incorporate the xcprivacy manifest. 
Reference: https://developer.apple.com/news/?id=3d8a9yyh

Actions needed: We need the compatible xcprivacy manifest version IOS SDK with xcprivacy manifest. We are expecting a seamless upgrade by upgrading to the latest version.

**Comment by jshier** [comment]
AlamofireImage isn't on the list of SDKs that require a manifest, nor do I believe it uses a restricted APIs, so it shouldn't need a manifest. If you are getting a warning from ASC, please include the warning message so I can narrow down the API that needs to be declared.

**Comment by andrewclements** [comment]
@jshier  The issue is that AlamofireImage links to an outdated version of Alamofire in the package dependencies here https://github.com/Alamofire/AlamofireImage/blob/master/Package.swift, can we get a new version with that updated to use Alamofire 5.9.1?
