### ISSUE TITLE
Feature request: force image transition if image is cached

### ISSUE THREAD

**Issue by jarrodrobins** [Alamofire/AlamofireImage#50]
In the readme for this project, there's the line - 

    If the remote image is cached locally, the image transition is ignored.

This makes perfect sense in most cases. However, I have a use case where I would like to force the transition to be invoked - for cross dissolving a background image that may already have been downloaded elsewhere in the app. 

Can I suggest some sort of override that we can use to ensure that the animation is not ignored if the image is in a cache? 

I'm happy to create a pull request myself but I'd like others to agree on the implementation first. 

The easiest solution would be to just add an extra optional parameter to `af_setImageWithURLRequest`.

Thoughts?

**Comment by cnoon** [comment]
Hmmmm...could you provide me some more details on why you need to do this? I want to make sure it's a fairly common use case before we modify anything in AlamofireImage. This use case seems a bit off the common path to me.

**Comment by jarrodrobins** [comment]
What I'm using it for is essentially a "Now Playing" screen along the lines of Spotify. You've got cards of album art which the user can swipe on, and a blown up, blurred background image which crossfades when the user changes what's playing. 

So, AlamofireImage is fine for the cards - they don't need to fade in. But, the background needs to consistently fade whether the image is cached or not otherwise it looks a bit janky. 

I suppose this can be handled via `ImageDownloader` and applying some animation elsewhere, but it'd be nice to have the flexibility to tell AlamofireImage not to ignore the transition just because it's cached the image before.

**Comment by cnoon** [comment]
Sounds good @jarrodrobins...I'm convinced. Your approach also sounds correct. Would you mind putting together a PR for this as well as some tests?

**Comment by jarrodrobins** [comment]
Sure. I'm a bit busy this week but I'll hopefully have some time next weekend to put something together. :+1:

**Comment by cnoon** [comment]
Closing this issue out...please redirect all comments to #53.
