### ISSUE TITLE
AspectScaledToFillSizeFilter

### ISSUE THREAD

**Issue by joaopedrok** [Alamofire/AlamofireImage#52]
Hi,

im getting a little problem with AspectScaledToFillSizeFilter.

when i use this

cell.eventImageView!.image = image!.af_imageAspectScaledToFillSize(cell.eventImageView!.bounds.size) 

i get a result that next what i want.

but when i use 

let imgFilter = AspectScaledToFillSizeFilter(size: cell.eventImageView!.bounds.size)
        cell.eventImageView!.af_setImageWithURL(NSURL(string: url!)!, placeholderImage: nil, filter: imgFilter, imageTransition: UIImageView.ImageTransition.CrossDissolve(0.5))

i get a different thing. Looks like that my filter is not being applied to my UIImageView.

Does anyone know about it?

**Comment by cnoon** [comment]
Screenshots? Is the `URL` pulling down the same image as your first example?

**Comment by joaopedrok** [comment]
Yes is the same.

This happen when i use the second.
![simulator screen shot 22 de nov de 2015 21 15 42](https://cloud.githubusercontent.com/assets/8363865/11326944/5435d8c6-915e-11e5-9686-2956868038d1.png)

 This happen when i use the first. This is what i want

![simulator screen shot 22 de nov de 2015 21 16 03](https://cloud.githubusercontent.com/assets/8363865/11326945/5619843a-915e-11e5-9144-9f0e2eb27c9f.png)

**Comment by cnoon** [comment]
Hmmmm...where'd your screenshots go? I received the email? Either way, would you be able to put together a small sample project demonstrating the issue? This would make it MUCH easier to track down the issue.

**Comment by cnoon** [comment]
Hi @joaopedrok, could you please get back to me about my previous comment? If not, I'm going to close this issue out.

**Comment by joaopedrok** [comment]
So,

this part of code

 cell.eventImageView!.af_setImageWithURL(NSURL(string: url!)!, placeholderImage: nil, filter: AspectScaledToFillSizeFilter(size: cell.eventImageView!.bounds.size), imageTransition: UIImageView.ImageTransition.CrossDissolve(0.5))

Is giving me this two different images.

<img width="438" alt="captura de tela 2015-12-05 as 11 52 14" src="https://cloud.githubusercontent.com/assets/8363865/11608080/ce1b7672-9b46-11e5-8e2a-90e10f7cb3e3.png">
<img width="439" alt="captura de tela 2015-12-05 as 11 51 59" src="https://cloud.githubusercontent.com/assets/8363865/11608081/d01aca7c-9b46-11e5-9eed-55ef671dafc8.png">


take a look at the left top corner of the image with the text "Scrolls". There is diference in loading the image.

Can you tell me how to solve it?

This is an UIImageView inside a UITableViewCell with the scale type in AspectFill and ClipToBounds setted to true.

Im sorry the delay in answer.

**Comment by cnoon** [comment]
There are a few things I can think of that may be causing the issue, but it's difficult to know for sure without seeing a sample project demonstrating the issue. Would it be possible for you to post one? If not, here are the possible culprits:

1. Your `cell.eventImageView!.bounds.size` could be reporting different sizes depending on where you are in your layout passes. You could print out this value to make sure it's the same or hard-code the value just to make sure.
1. You should not be mixing both an `AspectScaledToFillSizeFilter` and a `contentMode` of `AspectFill` together. You also shouldn't need to `ClipToBounds`. I'd recommend setting the `contentMode` to `.Center`.

Most likely, one of these changes will fix up your issue. I'm going to go ahead and close this issue out for now. If this doesn't fix your issue, then we're going to need some more info to go on...most likely a sample project.

Best of luck! 🍻
