### ISSUE TITLE
UInt64 cannot be negative

### ISSUE THREAD

**Issue by frogcjn** [Alamofire/AlamofireImage#56]
In ImageCache.swift
```
                let bytesToPurge = self.currentMemoryUsage - self.preferredMemoryUsageAfterPurge
```
This sentence may EXC_BREAKPOINT, because self.currentMemoryUsage may less then self.preferredMemoryUsageAfterPurge.

and bytesToPruge is UInt64 type inference by Swift.

**Comment by cnoon** [comment]
Thanks for reporting @frogcjn!

I would say that if you end up seeing this error, then you have set up the `memoryCapacity` and the `preferredMemoryUsageAfterPurge` parameters incorrectly. To help guard against this moving forward, I've added a `precondition` to the `ImageCache` initializer in 0095691b to prevent you from accidentally making this mistake.

Thanks again. 🍻
