### ISSUE TITLE
Image Inflate code between AFNetworking & AlamofireImage

### ISSUE THREAD

**Issue by puttin** [Alamofire/AlamofireImage#66]
The AFNetworking version is AFInflatedImageFromResponseWithDataAtScale which has nearly 90 lines code.

But AlamofireImage's is just
CGDataProviderCopyData(CGImageGetDataProvider(CGImage))

I wonder 
1. why the difference?
2. a copy without CGDataProviderRelease is fine?

**Comment by cnoon** [comment]
AFNetworking and Alamofire are not designed to be the same libraries. Alamofire was designed over three years after the original AFNetworking was built. There are some VERY large differences between the two libraries. You should not expect them to be exactly the same. Large portions of AFNetworking were designed for APIs much older than those available today.

The image inflation logic was rebuilt from the ground up in AlamofireImage. The reason that only `CGDataProviderCopyData` is called to inflate the image is that that's all that is required. This took a long time to figure out in the debugger. To your second question, CoreGraphics objects are automatically memory managed in Swift. You don't (and can't) need to call `CGDataProviderRelease` anymore.

Cheers. 🍻
