### ISSUE TITLE
Feature request: optional inflateResponseImage parameter in ImageDownloader's API

### ISSUE THREAD

**Issue by puttin** [Alamofire/AlamofireImage#67]
as title

**Comment by cnoon** [comment]
The `ImageDownloader` is already auto-inflating any image that is downloaded. It uses the default values of the [imageResponseSerializer] which are set to automatically inflate by default. This also means that the images stored in the ImageCache are all already inflated which seems to me to be what you would always want. Therefore, it seems incorrect to me to expose the property to control inflation in the ImageDownloader APIs.

The only argument for doing this that I can think of would be to disable inflation. The problem though is that I cannot think of why you would ever actually want to do that. If you're using the ImageDownloader, then you're trying to download images into memory for use. If you are trying to just download files to disk, then you should use Alamofire directly.

I'm going to close this issue out for now. If you can provide some additional context here to help make a convincing case, then I'll be happy to re-open and continue to investigate.

Cheers. 🍻

**Comment by puttin** [comment]
Yes，I end up with fork ImageDownloader to my own FileDownloader.
Thanks!

**Comment by iad24** [comment]
Hi. I noticed the line 'CGDataProviderCopyData(CGImageGetDataProvider(CGImage))' of function af_inflate uses a lot of memory especially when I load a large image on a cell (like 3000x3000 and file size is 2MB) and then scroll the pages quickly. This blows up the memory usage and crashes my app

Disabling the inflation works for me

**Comment by puttin** [comment]
@iad24 How about create a new issue about this problem? 
Link it with this issue if you will.
