### ISSUE TITLE
Installing and building from Carthage fails on the watchOS scheme

### ISSUE THREAD

**Issue by ivan-konov** [Alamofire/AlamofireImage#69]
I am setting up my Cartfile as explained in the readme file and I get this console output when running "carthage update".

---

*** Fetching AlamofireImage
*** Fetching SDWebImage
*** Fetching Alamofire
*** Checking out Alamofire at "3.1.4"
*** Checking out AlamofireImage at "2.2.0"
*** Checking out SDWebImage at "3.7.3"
*** xcodebuild output can be found in /var/folders/pr/vgdvxhm93yjbq8_9w4p2q_z80000gn/T/carthage-xcodebuild.bnxNOt.log
*** Building scheme "Alamofire OSX" in Alamofire.xcworkspace
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)
A shell task failed with exit code 65:
** BUILD FAILED **

The following build commands failed:
	Check dependencies
(1 failure)

**Comment by cnoon** [comment]
What version of Carthage and what version of Xcode?

**Comment by ivan-konov** [comment]
Carthage: 0.10.0
Xcode: 7.2

**Comment by cnoon** [comment]
Could you update to Carthage 0.11.0 and retry?

**Comment by ivan-konov** [comment]
That was the problem. Thank you!
