### ISSUE TITLE
Default closure based ImageFilter struct

### ISSUE THREAD

**Issue by damienrambout** [Alamofire/AlamofireImage#7]
I think many people will like to create filters on the fly with something like that:
```swift
let filter = ImageFilter("MyFilter") { image in
    // Do something the image
   return image.someTransformation()
}
```
It would be really convenient in some cases to avoid creating many files for isolated cases. In this example, the filter would have `"MyFilter"` as its identifier. (I don't think we can automatically generate a same unique identifier for this on-the-fly filter every time it is created / copied)

This would require to rename the protocol `ImageFilter` into `ImageFilterType`.

---

The same could be applied to (to be announced) `CompositeImageFilter` type. It could be created with a variadic array of `ImageFilterType` ~~or a variadic array of `Image -> Image` closures / functions~~.
```swift
let composite = CompositeImageFilter(filters: SizeToFillFilter(size: size), CircleFilter(), BlackAndWhiteFilter())
```

`CompositeImageFilter` protocol would be renamed `CompositeImageFilterType`.

**Comment by damienrambout** [comment]
We can even think of a custom operator to create composite image filters:
```swift
let filter = SizeToFillFilter(size: size) => CircleFilter() => MyCustomFilter()
```
which is clearer and shorted than:
```swift
let filter = CompositeImageFilter(filters: SizeToFillFilter(size: size), CircleFilter(), MyCustomFilter())
```

**Comment by cnoon** [comment]
I think something like `DynamicImageFilter` or `CustomImageFilter` that takes an identifier and trailing filter closure in the initializer could definitely be useful. If you want to take a stab at this along with some tests, that would be awesome!

As for a similar type of `CompositeImageFilter`, I think it would be good to have one that has an initializer that takes an array of filters. I think a variadic initializer is fine as well. How about both? Also, how about a name like `DynamicCompositeImageFilter`?

Now as for adding operator overloads, I'm hesitant. If you'd like to put that together in the PR, then I'll gladly take a look. No promises though on actually merging that. Just thinking through it off the top of my head it would have to merge two `ImageFilter` comforming objects into a `CompositeImageFilter`, then append additional filters into the composite. It would certainly be more clear and only slightly more verbose to use a variadic initializer on the `DynamicCompositeImageFilter`. My two cents...

**Comment by damienrambout** [comment]
@cnoon ok, let's first start with `DynamicImageFilter` and `DynamicCompositeImageFilter`. I think we'll have to use them before deciding wether custom operators are useful for creating composite filters.
I'll try to PR in the next few days.

**Comment by cnoon** [comment]
Okay sounds great. Just let me know if you need anything from me!

**Comment by cnoon** [comment]
Completed in #14.
