### ISSUE TITLE
Xcode complains that watchOS framework was built for iOS when installed through Carthage

### ISSUE THREAD

**Issue by ivan-konov** [Alamofire/AlamofireImage#70]
I get this error when I try to add the 2 frameworks(Alamofire & AlamofireImage) to my WatchKit Extension target.
It actually does not matter from which platform Build folder I will add the frameworks. It always shows the same error.
---

d: building for watchOS simulator, but linking against dylib built for iOS, file '/Some-Project-Filder/Carthage/Build/iOS/AlamofireImage.framework/AlamofireImage' for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)

**Comment by cnoon** [comment]
What version of Xcode and what version of Carthage? Make sure you're running Carthage 0.11.0.

**Comment by ivan-konov** [comment]
Xcode is 7.2, Carthage is 0.11.0

**Comment by cnoon** [comment]
I just checked out the project structure and it looks correct from what I can tell. Would you be willing to open an issue with Carthage to rope in the experts?

**Comment by ivan-konov** [comment]
I have added the same issue on their profile. I would suggest that we leave this open so people that will come looking here will have a clue where to look.

**Comment by ivan-konov** [comment]
The problem was with the Framework Search Paths build setting. I had added previously another library installed through Carthage. Thus it had retained the path to the iOS build folder. Removing it fixed the problem.

**Comment by cnoon** [comment]
Sweet. Glad you figured it out.

**Comment by ivan-konov** [comment]
They should add a "Like" button :D
