### ISSUE TITLE
Need API to set inflateResponseImage to false

### ISSUE THREAD

**Issue by iad24** [Alamofire/AlamofireImage#72]
Hi. I noticed the line 'CGDataProviderCopyData(CGImageGetDataProvider(CGImage))' of function af_inflate uses a lot of memory especially when I load a large image on a cell (like 3000x3000 and file size is 2MB) and then scroll the pages quickly. This blows up the memory usage and crashes my app

Disabling the inflation works for me

**Comment by jshier** [comment]
You'll need to clarify how you're using the AlamofireImage API in order for us to help you. However, if you're making image download requests directly, you can already configure inflation in the `.responseImage()` method.

**Comment by iad24** [comment]
I download the image for my UIImageView using the function af_setImageWithURL().

**Comment by jshier** [comment]
We'll look into adding inflation control to that API. In the meantime, you could manually download images without inflation and set them on the image view.

**Comment by iad24** [comment]
Ok. thanks man!

**Comment by cnoon** [comment]
How many images are you loading this way @iad24? I'm hesitant to think the memory issue is due to inflation. I'm much more inclined to think your memory issue is coming from somewhere else. Could you produce a sample app or some sample code that can repro this issue? Are you using a particular type of image?

**Comment by designatednerd** [comment]
I believe I've run into something similar. Downloading a whole bunch of images from URLs using the `ImageDownloader`, I'm seeing this delightful memory growth graph: 

<img width="391" alt="screen shot 2016-02-10 at 4 32 30 pm" src="https://cloud.githubusercontent.com/assets/1976498/12964113/f03e4e30-d013-11e5-9e67-5dca569246a5.png">

Going through instruments I've seen a bunch of nonsense and leaks around setting up caches with the `NSURLSession`. Found [this similar issue on the Hockey SDK](https://github.com/bitstadium/HockeySDK-iOS/issues/237) with [a fix](https://github.com/bitstadium/HockeySDK-iOS/commit/947afd2f3380b0525cf59447a21a94886a4c7cf4) around making sure the session actually finishes its tasks. FWIW this is also Xcode 7.2 and iOS 9.2.  

Going to see if I can figure anything out over the next couple days, but figured I'd throw it out in case it gives anyone any bright ideas before that.

**Comment by cnoon** [comment]
Thank you for the information @designatednerd. Would it be possible for you to run the same tests with disabling the auto-inflation? That can be done by commenting out this [line](https://github.com/Alamofire/AlamofireImage/blob/master/Source/Request%2BAlamofireImage.swift#L96) in the `Request` extension.

**Comment by designatednerd** [comment]
@cnoon Just an update, the problem wound up being on my end. The amount of time spent inflating images wound up being a symptom of the fact that a couple operations I was doing weren't actually as efficient as they should have been. 

FWIW for anyone else looking in to something like this, the couple things I had to do were a) Trace back where all the calls were coming from and figure out why they were hitting the download every single time when I had a separate cache things should have been coming from and b) Make sure a couple memory-intensive operations were wrapped in `autoreleasepool` blocks - for some reason ARC wasn't grabbing the memory back fast enough if I didn't explicitly wrap those operations in an auto-release pool.

**Comment by cnoon** [comment]
Thank you for your feedback here @designatednerd...much appreciated! 🍻

I'm going to go ahead and close this issue out. If anyone finds an issue here, please comment and I'll be happy to reopen.

**Comment by cnoon** [comment]
I'm actually going to keep this open since I think we may need to open up the `inflateResponseImage` parameter.

**Comment by iad24** [comment]
@cnoon Hmmm. I actually created a simple demo for this and it seems the app is not crashing. So something wrong with my original app XD. But thanks for keeping this open. Btw, what does CGDataProviderCopyData do? 

@designatednerd thanks for the info. I will take a look on this

**Comment by cnoon** [comment]
@iad24, [CGDataProviderCopyData](https://developer.apple.com/library/prerelease/ios/documentation/GraphicsImaging/Reference/CGDataProvider/index.html#//apple_ref/c/func/CGDataProviderCopyData) just performs a deep copy of the data and will inflate it before doing so.

**Comment by cnoon** [comment]
After giving this a bunch of thought, I think it's best to not expose the inflation property in the `UIImageView` extension APIs. It's only going to cause problems. If you don't want to run the inflation logic on an image due to memory issues, you shouldn't be using the `UIImageView` extension at all. Because of this, I think we'll keep the design as is for now unless we find an extremely good reason for doing so.

Thanks everyone for all the feedback here. 

Cheers. 🍻
