### ISSUE TITLE
How to make perfect code for image caching from url[For Beginner Code Help]

### ISSUE THREAD

**Issue by htarwara6245** [Alamofire/AlamofireImage#73]
I know its sounds like crazy.But,for a beginner like me,the documentation seems a little confuse.
So,If I can let me request a help from you because I want to use your library instead of KingFisher.
First of all,I have realm database which i used to store notification information.Every time the notifications comes in,it include data and 2 image url,

What i did in my program was,I insert every notifications that comes in at realm database and get all the data and then show at table cell.When each table cell is tapped,the detail goes on.

So,there will be one image at table view which will be max 50 records [1 image for each row] and,two images will be showed at the detail view when user tapped one of table view cell.

For,the table view which have 50 records max(let assume 10 notifications comes in)
How to download the 10 images asynchronously and cache and show the user?Even the user remove the app from app switcher and open again,the image should be still remain without needing to re-download again

This is the code that I applied at my table view (cellForRowAtIndexPath) for one notification only.
```
        let URL = NSURL(string: notification.image1)! // notification is realm object,there was image 1 & 2
       // image1 for list view and,both for detail view when user tapped on each record.
        let placeholderImage = UIImage(named: "Notification_PlaceHolder")!
        
        cell.notificationImageView.af_setImageWithURL(
            URL,
            placeholderImage: placeholderImage,
            imageTransition: .CrossDissolve(0.5)
        )
```

Any help please?

**Comment by jshier** [comment]
AlamofireImage uses the standard `NSURLCache` to cache responses. If your server properly returns a response indicating the system should use the local copy, then that's what will happen. Otherwise you'll need to customize the `ImageDownloader` used by the `UIIImageView` extension by providing your customized instance to `UIImageView.af_imageDownloader`. By doing this you can ensure the app keeps using the local data despite the server response.
