### ISSUE TITLE
Adding additional headers to af_setImageWithURL

### ISSUE THREAD

**Issue by multiholle** [Alamofire/AlamofireImage#74]
Is it possible to add request headers when loading an image from url? Currently I'm using UIImageView#af_setImageWithURL. I need to support additional headers to comply our api.

**Comment by parkej60** [comment]
Also wondering if this is possible. Need to support the Authorization Header.

**Comment by werediver** [comment]
This is possible by providing `ImageDownloader` with a custom `Alamofire.Manager` subclass where you should override `request(URLRequestConvertible)` to add extra headers to each request.

You can also try to set your extra headers in session configuration, but that won't work for `Authorization` header.

**Comment by felipeplets** [comment]
This definitively should be easier like a setHeaders method or a parameter to the af_setImageWithURL.

**Comment by jshier** [comment]
You can provide a custom `ImageDownloader` to `UIImageView.af_imageDownloader` which has custom headers set per @werediver's suggestion. 

Also, while `af_setImageWithURL` doesn't provide the full suite of options Alamofire's various `request()` methods do, it does support `URLRequestConvertible`, which lets you provide an conforming type to generate the `NSURLRequest` used to request the image. This is where you should add any headers you need for your image downloads. And really, if you app is making more than a couple requests, using something like the [Router pattern described in the Alamofire docs](https://github.com/Alamofire/Alamofire#crud--authorization) is a much better pattern than creating raw requests.
