### ISSUE TITLE
Bug with AlamoFireImage

### ISSUE THREAD

**Issue by patchthecode** [Alamofire/AlamofireImage#75]
myProg(63494,0xb029b000) malloc: *** error for object 0x79b5ce80: double free
*** set a breakpoint in malloc_error_break to debug

<img width="725" alt="screen shot 2016-01-22 at 4 25 25 am" src="https://cloud.githubusercontent.com/assets/2439146/12510630/30ec683a-c0c0-11e5-97dd-2e9b48fb4b98.png">

**Comment by jshier** [comment]
Is it possible for your to provide some of your calling code? We're unlikely to be able to fix this without knowing how it's triggered.

**Comment by patchthecode** [comment]
Here is my calling code:

```
class ImageLoaderWorker {
    private let imageCache = AutoPurgingImageCache()
    private let imageDownloader = ImageDownloader(
        configuration: ImageDownloader.defaultURLSessionConfiguration(),
        downloadPrioritization: .FIFO,
        maximumActiveDownloads: 5,
        imageCache: AutoPurgingImageCache())
    
    var imageLinks:   [String] = []
    var imageCacheID: [String] = []
    

    
    func downloadBatchOfImages(completionHandler:(imageArray: [UIImage?])->Void) {
        
        var count: Int = imageLinks.count
        var images = [UIImage?](count: count, repeatedValue:nil)
        
        // Convert URL strings into URL objects
        var urls: [URLRequestConvertible] = []
        for imageLink in imageLinks {
            let urlRequest = NSURLRequest(URL: NSURL(string: imageLink)!)
            urls.append(urlRequest)
        }
    
        // Begin downloading images
        imageDownloader.downloadImages(URLRequests: urls, filter: nil) { (response) -> Void in
            let urlStringJustDownloaded = response.request?.URL?.absoluteString
            let indexToInsert = self.imageLinks.indexOf(urlStringJustDownloaded!)!
            
            if let image = response.result.value {
                
                // jt101 Should i cache images here?
                images[indexToInsert] = image

            } else {
                print ("something went wrong. Image was not loaded in ImageLoaderWorker")
                // something went wrong is downloading the file. Use default image.
                images[indexToInsert] = UIImage(named: "1.jpg")
            }
            
            count--
            
            // TODO: What if the image does not download?
            if count < 1 {
                completionHandler(imageArray: images)
            }
        }
    }
}
```

**Comment by cnoon** [comment]
Is there any chance you could submit a sample project that reproduces this behavior @patchthecode? That would make it much easier to diagnose if there's actual an AFI issue here or something with your logic. Nothing you posted in your example looks problematic.

**Comment by patchthecode** [comment]
ok, its part of a larger project. I will scale out the problem part and submit it in a while

**Comment by cnoon** [comment]
After thinking through this some more, I'm almost positive this is due to the non-thread safe UIImage initializer. I'm going to switch the response serializer over to using the thread-safe initializer. I should have done this right from the start.

**Comment by cnoon** [comment]
Should be resolved with 85048ff4. @patchthecode, if you could retest with the latest commits on `master`, that would be great!

**Comment by cnoon** [comment]
I'll gladly re-open this issue if the problem persists.

**Comment by patchthecode** [comment]
Ok. I am using this framework from cocoa pods. I just did a 'Pod Install' to update the framework.
If the problem happens again, will let you know. Thanks for your awesome work

**Comment by patchthecode** [comment]
Happened again today. I did a Pod init (in cocoa pod.. i assume the update you did is already there?)

<img width="972" alt="screen shot 2016-02-08 at 12 28 52 am" src="https://cloud.githubusercontent.com/assets/2439146/12880998/17546830-cdfb-11e5-8480-92317c399f0e.png">

<img width="978" alt="screen shot 2016-02-08 at 12 30 34 am" src="https://cloud.githubusercontent.com/assets/2439146/12881013/337f95e8-cdfb-11e5-8466-ae69265d65f5.png">

**Comment by cnoon** [comment]
Are you loading any other images using `UIImage(data:)` or `UIImage(data:scale:)` in your code outside of AlamofireImage? If yes, that's certainly the issue. Additionally, you do not have the 2.3.1 release. That has been updated to use the thread-safe `UIImage` [initializer](https://github.com/Alamofire/AlamofireImage/blob/master/Source/Request%2BAlamofireImage.swift#L142-L144).

**Comment by patchthecode** [comment]
No i am not loading any other images outside of alamoFireImage. However, i just looked at what you said about the release number. Seems i was still using version 2.2 in my Cocoapod file. I have now changed version to *** pod 'AlamofireImage', '~> 2.3'  ***   and did an update. It the error happens again after this update, then i will just give you a copy of the problem code so that you can run it. Thanks for the help. Will update you if it happens again after the update.

**Comment by patchthecode** [comment]
Update: Since after updating. No more crashes. And i'm not get the BOMStorage file warning messages anymore. All seems well. Thanks for your work. Have a good one.

**Comment by cnoon** [comment]
That's great to hear @patchthecode! Thanks for reporting that back to us.
