### ISSUE TITLE
Know when af_setImageWithURL load the image

### ISSUE THREAD

**Issue by boardmain** [Alamofire/AlamofireImage#82]
how i can be notified when af_setImageWithURL  finished to download the remote image?

**Comment by patchthecode** [comment]
Have you tried the method --> af_setImageWithURL(URL:placeholderImage:filter:imageTransition:runImageTransitionIfCached:completion:-> Void)? method?

It has a completion handler.

**Comment by cnoon** [comment]
Thanks @patchthecode! That is exactly why the `completion` closure is exposed in the most detailed API @boardmain. Cheers. 🍻

**Comment by boardmain** [comment]
thank you all
