### ISSUE TITLE
Remove image from the cache

### ISSUE THREAD

**Issue by heshjit** [Alamofire/AlamofireImage#85]
Hi,

I have fetched the image using the below code inside a function in UIImageView extension.
`        self.af_setImageWithURL(url, placeholderImage: nil, filter: nil, imageTransition: .None, runImageTransitionIfCached: false, completion: {`
`response in`
           ` if response.data != nil {`
               `self.image = UIImage(data: response.data!)`
           ` }`
        `})`

sometimes I need to get the fresh image from the url again without fetching from the cache. In order to achieve this I removed the image from imageCache and URLCache using below code.
       ` let imageDownloader = UIImageView.af_sharedImageDownloader`
      `let urlRequest = NSURLRequest(URL: url)`
         ` //Clear from in-memory cache`
` imageDownloader.imageCache?.removeImageForRequest(urlRequest, withAdditionalIdentifier: nil)`
      ` //Clear from on-disk cache`
`imageDownloader.sessionManager.session.configuration.URLCache?.removeCachedResponseForRequest(urlRequest)`

but this is not working. When I call af_setImageWithURL there is no new network call to fetch the image from url, instead the image is fetched from the cache.

**Comment by cnoon** [comment]
Hi @heshjit,

First off, you should stop using the `completion` closure the way you are. AFI will automatically set the image on the image view if you set the `completion` closure to `nil`. You're currently setting the image on the image view twice.

Secondly, I'm not really sure why your logic isn't purging the image from memory and on-disk. I can't pinpoint the issue right now. With that said, I think what you are having to do is too difficult. You should have to remove the image from both caches, you should be able to use the URL request cache policy to tell the image view to reload the image from the network. The `ImageDownloader` already does this, but the `UIImageView` extension does not. I just added a card to our Trello backlog to update this functionality.

To debug your current solution, I'd recommend figuring out whether the image is still in the `ImageCache` or the `NSURLCache`. Once you figure out which one is not being purged, continue to investigate. I'm guessing you aren't purging things quite right.

I'm going to close this issue out for now. If you do end up finding a specific issue in AFI, please comment on this issue with more info and I'll be happy to re-open.

Cheers. 🍻

**Comment by heshjit** [comment]
hi @cnoon 

Thanks for your response.
The problem was that the url was not returning contentType image. After fixing this AlamofireImage worked perfectly.

Thanks
Heshjith

**Comment by cnoon** [comment]
Cool...thanks for letting us know!

**Comment by htarwara6245** [comment]
I tried the same thing in Swift 3. didn't work out...help?

```
func removeCacheForHomeContentImage(url: String) {
        let imageURL = URL(string : url)
        let urlRequest = Foundation.URLRequest(url: imageURL!)
        
        let imageDownloader = UIImageView.af_sharedImageDownloader
        
        // Clear the URLRequest from the in-memory cache
        let cache = imageDownloader.imageCache?.removeImage(for: urlRequest, withIdentifier: nil)
        // Clear the URLRequest from the on-disk cache
        
        imageDownloader.sessionManager.session.configuration.urlCache?.removeCachedResponse(for: urlRequest)
    }
```

**Comment by yura-voevodin** [comment]
Hello! I have the same issue :(

**Comment by kiraninfogird** [comment]
**Updated for swift: **

func clearImageFromCache(mYourImageURL: String) {
    let URL = NSURL(string: mYourImageURL)!
    let mURLRequest = NSURLRequest(url: URL as URL)
    let urlRequest = URLRequest(url: URL as URL, cachePolicy: URLRequest.CachePolicy.reloadIgnoringLocalAndRemoteCacheData)
    
    let imageDownloader = UIImageView.af_sharedImageDownloader
    _ = imageDownloader.imageCache?.removeImage(for: mURLRequest as URLRequest, withIdentifier: nil)
    self.mImageView.af_setImage(withURLRequest: urlRequest, placeholderImage: UIImage(named: "placeholder"), completion: { (response) in
        self.mImageView.image = response.result.value
    })
}
