### ISSUE TITLE
Set function runImageTransition as public

### ISSUE THREAD

**Issue by iad24** [Alamofire/AlamofireImage#90]
Maybe you could set some functions like runImageTransition to public so if we use the imageDownloader, we can re-use this function in applying the transition.
Or maybe you got better idea that I dont know? pls share

**Comment by cnoon** [comment]
Hi @iad24,

The [runImageTransition](https://github.com/Alamofire/AlamofireImage/blob/master/Source/UIImageView%2BAlamofireImage.swift#L339-L349) method in the `UIImageView` extension is already `public`. If you're looking for another way to do that generically, you can always make your own method that uses the same logic inside the `runImageTransition` implementation.

Cheers. 🍻

**Comment by iad24** [comment]
Opps. Yeah its public now after I installed the pod again. Weird. anyways, thanks =)
