### ISSUE TITLE
af_imageWithAppliedCoreImageFilter changes image size

### ISSUE THREAD

**Issue by arn00s** [Alamofire/AlamofireImage#93]
After applying a filter to an image, the size of the image changes.
How can I keep the original image size ?

`let blurredImage = resultImage.af_imageWithAppliedCoreImageFilter(
                            "CIGaussianBlur",
                            filterParameters: ["inputRadius": 3.5]
                        )`

Thanks,
Arnaud

**Comment by cnoon** [comment]
This was modified intentionally in 2db09fe7. If you need to keep it at the same size, then I'd suggest you use a second `ImageFilter` to scale it to the appropriate size.

Best of luck! 🍻
