### ISSUE TITLE
Build target for tvOS missing UIButton extension

### ISSUE THREAD

**Issue by picciano** [Alamofire/AlamofireImage#94]
I am trying to use AlamofireImage for a tvOS project, but the build target for tvOS seems to be missing the UIButton+AlamofireImage.swift.

Was that intentional? If not, could that get fixed? Thanks!

**Comment by picciano** [comment]
Pull request for this has been submitted.

**Comment by picciano** [comment]
The PR also addresses an issue where completion() was getting called before the image is set on the UIButton.

**Comment by cnoon** [comment]
Fixed in https://github.com/Alamofire/AlamofireImage/commit/3ea351807914fbf62b53b7d53094a48bfce4f18a. Please see #95 for more details.

Cheers. 🍻
