### ISSUE TITLE
Images cached to disk not loaded until af_setImageWithURL called?

### ISSUE THREAD

**Issue by calsmith** [Alamofire/AlamofireImage#96]
I'm experiencing weird behaviour when trying to retrieve an image that is in the disk cache but not in the memory cache.
If I call af_setImageWithURL, the image is downloaded and cached to the disk as expected.

The second time I launch the app, I call af_setImageWithURL and the image is loaded from the disk as expected. However, when I call imageForRequest it is still nil.

imageForRequest only ever returns the image after af_setImageWithURL has been called at least once - even if the image already exists in the disk cache.

It seems like imageForRequest ignores the disk cache and only uses the memory cache. Is this the expected behaviour or a bug? If the former, what is the correct way to retrieve an image from _either_ the disk or memory cache?

```
      // Download image or fetch from cache.
      let cache = UIImageView.af_sharedImageDownloader.imageCache;
      let url = NSURL(string: "https://upload.wikimedia.org/wikipedia/commons/e/e0/Clouds_over_the_Atlantic_Ocean.jpg")!;
      iconView.af_setImageWithURL(url);
      
      // Retrieve image from memory or disk.
      let req = NSURLRequest(URL: url);
      if let _ = cache?.imageForRequest(req, withAdditionalIdentifier: nil) {
         // Image is set the second time imageForRequest is called.
         print("image in cache!");
      } else {
         // Image is always nil the first time imageForRequest is called per app launch.
         // (even if the image has been cached to disk from a previous launch).
         print("image somehow not in cache?");
      }
```
Thank you!

**Comment by cnoon** [comment]
Your observation is exactly how the image caching was designed to work. It is only an in-memory cache, not an on-disk cache. Therefore, asking the `ImageCache` directly for the on-disk image will never return the on-disk image.

Calling the `af_setImageWithURL` API will load the image from the on-disk cache, put it in the in-memory cache and apply it to the image view. Then, calling `imageForRequest` after that happens will return the in-memory image. This design leverages all the power of `NSURLCache` along with the customization of the `ImageCache`.

You can find a bunch more info and history on this topic in https://github.com/Alamofire/AlamofireImage/issues/5.

Cheers. 🍻
