### ISSUE TITLE
Cache not working and af_setImageWithURL always show transition

### ISSUE THREAD

**Issue by DesmondPang** [Alamofire/AlamofireImage#99]
I use af_setImageWithURL in an UITableView. It always show the transition when I scroll the tabview repeatedly. Also, I check the cache.memoryUsage value. It always keep 0 even all images have been downloaded.

PS: I used this method in my past project, there is no such issue. 

   if let img = object.images.first{
            cell.thumbnailView.af_setImageWithURL(
                NSURL(string: (img.url))!,
                placeholderImage:PLCAEHOLDER_IMAGE_Default_Placeholder,
                imageTransition:.CrossDissolve(1.25),
                runImageTransitionIfCached:false
            )
        }

**Comment by cnoon** [comment]
Hi @DesmondPang,

We have MANY integration tests built around this logic, all of which pass on all platforms. Additionally, the iOS Example project demonstrates exactly what it is you're trying to do. I just verified all the functionality that you posted in your code sample does in fact work correctly in the example app. I'd recommend you check out the example app for how to use this functionality correctly.

If you do still have issues, I'd encourage you to put together a small sample app demonstrating your issues. This would make it much easier to help you. If you do end up providing more info here that leads us to believe there is an issue in AlamofireImage, I'll be happy to re-open and investigate further.

Cheers. 🍻

**Comment by DesmondPang** [comment]
I found that the number of images in self.cachedImages array of ImageCache class does not increase properly when I scroll the tableview. The count keeps changing and no more than 10. It means that it keeps adding new images to the cache and delete the old images at the same time. The images only about 300 kB and the memory usage shown on Xcode is about 200mb. I don't know why it only cache several images. That's why it keeps showing transition when I scroll the tableview.

**Comment by DesmondPang** [comment]
I added 

let imageCache = AutoPurgingImageCache(
    memoryCapacity: 100 * 1024 * 1024, 
    preferredMemoryUsageAfterPurge: 60 * 1024 * 1024
)

but it does not work for af_setImageWithURL extension. How to change the cache size if I only use af_setImageWithURL.??

**Comment by DesmondPang** [comment]
Finally, I fixed it.

Customised cache and downloader

  let imageCache = AutoPurgingImageCache(
            memoryCapacity: 900 * 1024 * 1024,
            preferredMemoryUsageAfterPurge: 600 * 1024 * 1024
        )

        
        UIImageView.af_sharedImageDownloader = ImageDownloader(
            configuration: ImageDownloader.defaultURLSessionConfiguration(),
            downloadPrioritization: .FIFO,
            maximumActiveDownloads: 10,
            imageCache:imageCache
        )

**Comment by cnoon** [comment]
Awesome...glad you got things resolved!
